using System.Security.Claims;
using Hop.Api.Authorization;
using Hop.Api.Data;
using Hop.Api.DTOs;
using Hop.Api.Models;
using Hop.Api.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Hop.Api.Controllers;

[ApiController, Authorize]
public sealed class FleetMaintenanceController(AppDbContext db, IDomainEventPublisher events, FleetMaintenanceAttachmentStorage storage, FleetMaintenanceMileageAuthorizationService mileageAuthorization) : ControllerBase
{
    [HttpGet("/api/fleet/maintenance"), RequirePermission(FleetPermissions.MaintenanceView)]
    public async Task<ActionResult<ApiResponse<object>>> List([FromQuery] Guid? vehicleId, [FromQuery] Guid? maintenanceTypeId, [FromQuery] string? status, [FromQuery] bool overdueOnly = false, [FromQuery] int page = 1, [FromQuery] int pageSize = 25, CancellationToken ct = default)
    { page = Math.Max(1, page); pageSize = Math.Clamp(pageSize, 1, 100); var q = db.FleetVehicleMaintenanceSchedules.AsNoTracking().Where(x => x.IsActive); if (vehicleId != null) q = q.Where(x => x.VehicleId == vehicleId); if (maintenanceTypeId != null) q = q.Where(x => x.MaintenanceTypeId == maintenanceTypeId); if (!string.IsNullOrWhiteSpace(status)) q = q.Where(x => x.Status == status); if (overdueOnly) q = q.Where(x => x.DueDate < DateTime.UtcNow || x.DueMileage < x.Vehicle!.CurrentMileage); var total = await q.CountAsync(ct); var rows = await q.OrderBy(x => x.DueDate).Skip((page - 1) * pageSize).Take(pageSize).Select(x => new { x.Id, x.VehicleId, Vehicle = x.Vehicle!.VehicleCode, x.MaintenanceTypeId, Type = x.MaintenanceType!.Name, x.DueDate, x.DueMileage, x.Status, DueState = x.Status == FleetMaintenanceStatuses.InProgress ? "IN_PROGRESS" : x.DueDate < DateTime.UtcNow || x.DueMileage < x.Vehicle.CurrentMileage ? "OVERDUE" : "UPCOMING", x.ConcurrencyToken }).ToListAsync(ct); return ApiResponse<object>.Ok(new { items = rows, total, page, pageSize }); }

    [HttpGet("/api/fleet/maintenance/{id:guid}"), RequirePermission(FleetPermissions.MaintenanceView)] public async Task<ActionResult<ApiResponse<object>>> Detail(Guid id, CancellationToken ct) { var row = await db.FleetVehicleMaintenanceSchedules.AsNoTracking().Include(x => x.Records).ThenInclude(x => x.Attachments).FirstOrDefaultAsync(x => x.Id == id, ct); return row is null ? NotFound(ApiResponse<object>.Fail("Maintenance not found.")) : ApiResponse<object>.Ok(row); }
    [HttpPost("/api/fleet/maintenance"), RequirePermission(FleetPermissions.MaintenanceManage)] public async Task<ActionResult<ApiResponse<object>>> Create(MaintenanceScheduleBody body, CancellationToken ct) { if (body.DueDate is null && body.DueMileage is null) return BadRequest(ApiResponse<object>.Fail("Due date or mileage is required.")); var actor = Actor(); var item = new FleetVehicleMaintenanceSchedule { VehicleId = body.VehicleId, MaintenanceTypeId = body.MaintenanceTypeId, DueDate = body.DueDate, DueMileage = body.DueMileage, ReminderDays = body.ReminderDays, ReminderMileage = body.ReminderMileage, RecurrenceDays = body.RecurrenceDays, RecurrenceMileage = body.RecurrenceMileage, Notes = body.Notes?.Trim(), CreatedByUserId = actor }; db.Add(item); Audit("FleetMaintenance.Created", item.Id, actor); await events.PublishAsync(new("FleetMaintenance.Created", "FLEET", "FleetMaintenance", item.Id, actor, HttpContext.TraceIdentifier, new { item.VehicleId, item.DueDate, item.DueMileage }, []), ct); await db.SaveChangesAsync(ct); return ApiResponse<object>.Ok(new { item.Id, item.ConcurrencyToken }); }
    [HttpPut("/api/fleet/maintenance/{id:guid}"), RequirePermission(FleetPermissions.MaintenanceManage)] public async Task<ActionResult<ApiResponse<object>>> Update(Guid id, MaintenanceScheduleBody body, CancellationToken ct) { var item = await db.FleetVehicleMaintenanceSchedules.FindAsync([id], ct); if (item is null) return NotFound(); if (item.ConcurrencyToken != body.ConcurrencyToken) return Conflict(ApiResponse<object>.Fail("Concurrency conflict.")); if (item.Status == FleetMaintenanceStatuses.Completed || item.Status == FleetMaintenanceStatuses.Cancelled) return Conflict(ApiResponse<object>.Fail("Closed maintenance cannot be edited.")); item.DueDate = body.DueDate; item.DueMileage = body.DueMileage; item.ReminderDays = body.ReminderDays; item.ReminderMileage = body.ReminderMileage; item.RecurrenceDays = body.RecurrenceDays; item.RecurrenceMileage = body.RecurrenceMileage; item.Notes = body.Notes?.Trim(); item.UpdatedAt = DateTime.UtcNow; item.UpdatedByUserId = Actor(); item.ConcurrencyToken = Guid.NewGuid(); await db.SaveChangesAsync(ct); return ApiResponse<object>.Ok(new { item.Id, item.ConcurrencyToken }); }
    [HttpPost("/api/fleet/maintenance/{id:guid}/start"), RequirePermission(FleetPermissions.MaintenanceManage)]
    public async Task<ActionResult<ApiResponse<object>>> Start(Guid id, MaintenanceStartBody body, CancellationToken ct)
    {
        var item = await db.FleetVehicleMaintenanceSchedules.Include(x => x.Vehicle).SingleOrDefaultAsync(x => x.Id == id, ct);
        if (item is null) return NotFound();
        if (item.Status != FleetMaintenanceStatuses.Active || item.ConcurrencyToken != body.ConcurrencyToken) return Conflict(ApiResponse<object>.Fail("Invalid state or concurrency conflict."));
        if (body.StartMileage is < 0) return BadRequest(ApiResponse<object>.Fail("Start mileage cannot be negative."));
        var actor = Actor(); var startedAt = body.StartedAt ?? DateTime.UtcNow;
        var record = new FleetVehicleMaintenanceRecord { VehicleId = item.VehicleId, MaintenanceScheduleId = item.Id, MaintenanceTypeId = item.MaintenanceTypeId, StartedAt = startedAt, StartMileage = body.StartMileage, Vendor = body.Vendor?.Trim(), Description = body.Note?.Trim(), CreatedByUserId = actor };
        db.Add(record); item.Status = FleetMaintenanceStatuses.InProgress; item.UpdatedAt = startedAt; item.UpdatedByUserId = actor; item.ConcurrencyToken = Guid.NewGuid(); Audit("FleetMaintenance.Started", id, actor);
        await events.PublishAsync(new("FleetMaintenance.Started", "FLEET", "FleetMaintenance", id, actor, HttpContext.TraceIdentifier, new { item.VehicleId, record.StartedAt }, []), ct); await db.SaveChangesAsync(ct);
        return ApiResponse<object>.Ok(new { item.Id, RecordId = record.Id, item.Status, item.ConcurrencyToken });
    }
    [HttpPost("/api/fleet/maintenance/{id:guid}/cancel"), RequirePermission(FleetPermissions.MaintenanceCancel)] public Task<ActionResult<ApiResponse<object>>> Cancel(Guid id, MaintenanceActionBody body, CancellationToken ct) => Change(id, FleetMaintenanceStatuses.Cancelled, "FleetMaintenance.Cancelled", body, ct);
    [HttpPost("/api/fleet/maintenance/{id:guid}/complete"), RequirePermission(FleetPermissions.MaintenanceComplete)]
    public async Task<ActionResult<ApiResponse<object>>> Complete(Guid id, MaintenanceCompleteBody body, CancellationToken ct)
    {
        if (body.Cost < 0) return BadRequest(ApiResponse<object>.Fail("Cost cannot be negative."));
        await using var transaction = await db.Database.BeginTransactionAsync(ct);
        var lockKey = $"fleet-maintenance:{id}";
        await db.Database.ExecuteSqlInterpolatedAsync($"SELECT pg_advisory_xact_lock(hashtext({lockKey}))", ct);
        var item = await db.FleetVehicleMaintenanceSchedules.Include(x => x.Vehicle).SingleOrDefaultAsync(x => x.Id == id, ct);
        if (item?.Vehicle is null) return NotFound(ApiResponse<object>.Fail("Maintenance not found."));
        if (item.Status != FleetMaintenanceStatuses.InProgress || item.ConcurrencyToken != body.ConcurrencyToken) return Conflict(ApiResponse<object>.Fail("Invalid state or concurrency conflict."));
        var actor = Actor(); FleetMileageDecision mileage;
        try { mileage = await mileageAuthorization.Validate(actor, item.Vehicle.CurrentMileage, body.CompletedMileage, body.OverrideReason, ct); }
        catch (ArgumentException ex) { return BadRequest(ApiResponse<object>.Fail(ex.Message)); }
        catch (UnauthorizedAccessException) { return Forbid(); }
        var completedAt = body.CompletedAt ?? DateTime.UtcNow; var startedAt = body.StartedAt ?? item.UpdatedAt ?? item.CreatedAt;
        if (completedAt < startedAt) return BadRequest(ApiResponse<object>.Fail("CompletedAt cannot be before StartedAt."));
        var record = await db.FleetVehicleMaintenanceRecords.SingleOrDefaultAsync(x => x.MaintenanceScheduleId == id && x.CompletedAt == null && !x.IsCancelled, ct)
            ?? new FleetVehicleMaintenanceRecord { VehicleId = item.VehicleId, MaintenanceScheduleId = item.Id, MaintenanceTypeId = item.MaintenanceTypeId, StartedAt = startedAt, CreatedByUserId = actor };
        if (db.Entry(record).State == EntityState.Detached) db.Add(record);
        record.CompletedAt = completedAt; record.CompletedMileage = body.CompletedMileage; record.Cost = body.Cost; record.Vendor = body.Vendor?.Trim() ?? record.Vendor; record.InvoiceNumber = body.InvoiceNumber?.Trim(); record.Description = body.Description?.Trim() ?? record.Description; record.Result = body.Result?.Trim(); record.NextDueDate = body.NextDueDate; record.NextDueMileage = body.NextDueMileage; record.UpdatedAt = DateTime.UtcNow; record.UpdatedByUserId = actor; record.ConcurrencyToken = Guid.NewGuid();
        item.LastCompletedRecordId = record.Id; item.Status = FleetMaintenanceStatuses.Completed; item.IsActive = false; item.UpdatedAt = DateTime.UtcNow; item.UpdatedByUserId = actor; item.ConcurrencyToken = Guid.NewGuid(); item.Vehicle.CurrentMileage = mileage.RetainedMileage;
        if (item.RecurrenceDays is not null || item.RecurrenceMileage is not null) db.Add(new FleetVehicleMaintenanceSchedule { VehicleId = item.VehicleId, MaintenanceTypeId = item.MaintenanceTypeId, DueDate = body.NextDueDate ?? (item.RecurrenceDays is null ? null : completedAt.AddDays(item.RecurrenceDays.Value)), DueMileage = body.NextDueMileage ?? (item.RecurrenceMileage is null ? null : mileage.RetainedMileage + item.RecurrenceMileage), ReminderDays = item.ReminderDays, ReminderMileage = item.ReminderMileage, RecurrenceDays = item.RecurrenceDays, RecurrenceMileage = item.RecurrenceMileage, CreatedByUserId = actor });
        if (mileage.IsOverride)
        {
            db.AuditLogs.Add(new AuditLog { UserId = actor, EffectiveActorUserId = mileage.EffectiveActorUserId, DelegationId = mileage.DelegationId, DelegatorUserId = mileage.DelegatorUserId, Action = "FleetMaintenance.MileageOverride", EntityName = "FleetMaintenance", EntityId = id.ToString(), OldValue = mileage.PreviousMileage.ToString(), NewValue = System.Text.Json.JsonSerializer.Serialize(new { MaintenanceId = id, item.VehicleId, mileage.SubmittedMileage, mileage.RetainedMileage }), Reason = body.OverrideReason!.Trim(), CorrelationId = HttpContext.TraceIdentifier });
            await events.PublishAsync(new("FleetMaintenance.MileageOverride", "FLEET", "FleetMaintenance", id, actor, HttpContext.TraceIdentifier, new { item.VehicleId, mileage.PreviousMileage, mileage.SubmittedMileage, mileage.RetainedMileage }, []), ct);
        }
        Audit("FleetMaintenance.Completed", id, actor); await events.PublishAsync(new("FleetMaintenance.Completed", "FLEET", "FleetMaintenance", id, actor, HttpContext.TraceIdentifier, new { item.VehicleId, record.CompletedMileage, CompletedWithMileageOverride = mileage.IsOverride }, []), ct); await db.SaveChangesAsync(ct); await transaction.CommitAsync(ct);
        return ApiResponse<object>.Ok(new { item.Id, RecordId = record.Id, item.ConcurrencyToken, CompletedWithMileageOverride = mileage.IsOverride, RetainedVehicleMileage = mileage.RetainedMileage });
    }

    [HttpGet("/api/fleet/maintenance-types"), RequirePermission(FleetPermissions.MaintenanceView)] public async Task<ActionResult<ApiResponse<object>>> Types(CancellationToken ct) => ApiResponse<object>.Ok(await db.FleetMaintenanceTypes.AsNoTracking().OrderBy(x => x.SortOrder).ToListAsync(ct));
    [HttpPost("/api/fleet/maintenance-types"), RequirePermission(FleetPermissions.MaintenanceManageTypes)] public async Task<ActionResult<ApiResponse<object>>> CreateType(FleetMaintenanceType body, CancellationToken ct) { body.Id = Guid.NewGuid(); body.CreatedAt = DateTime.UtcNow; body.CreatedByUserId = Actor(); db.Add(body); await db.SaveChangesAsync(ct); return ApiResponse<object>.Ok(body); }
    [HttpPut("/api/fleet/maintenance-types/{id:guid}"), RequirePermission(FleetPermissions.MaintenanceManageTypes)] public async Task<ActionResult<ApiResponse<object>>> UpdateType(Guid id, FleetMaintenanceType body, CancellationToken ct) { var item = await db.FleetMaintenanceTypes.FindAsync([id], ct); if (item is null) return NotFound(); if (item.ConcurrencyToken != body.ConcurrencyToken) return Conflict(ApiResponse<object>.Fail("Concurrency conflict.")); item.Name = body.Name.Trim(); item.Description = body.Description?.Trim(); item.Category = body.Category; item.IsDateBased = body.IsDateBased; item.IsMileageBased = body.IsMileageBased; item.BlocksAvailabilityWhenOverdue = body.BlocksAvailabilityWhenOverdue; item.IsActive = body.IsActive; item.UpdatedAt = DateTime.UtcNow; item.UpdatedByUserId = Actor(); item.ConcurrencyToken = Guid.NewGuid(); await db.SaveChangesAsync(ct); return ApiResponse<object>.Ok(item); }
    [HttpGet("/api/fleet/vehicles/{vehicleId:guid}/maintenance"), RequirePermission(FleetPermissions.MaintenanceView)] public async Task<ActionResult<ApiResponse<object>>> VehicleMaintenance(Guid vehicleId, CancellationToken ct) => ApiResponse<object>.Ok(await db.FleetVehicleMaintenanceSchedules.AsNoTracking().Where(x => x.VehicleId == vehicleId).OrderByDescending(x => x.CreatedAt).ToListAsync(ct));
    [HttpGet("/api/fleet/vehicles/{vehicleId:guid}/documents"), RequirePermission(FleetPermissions.MaintenanceView)] public async Task<ActionResult<ApiResponse<object>>> Documents(Guid vehicleId, CancellationToken ct) => ApiResponse<object>.Ok(await db.FleetVehicleDocuments.AsNoTracking().Where(x => x.VehicleId == vehicleId && x.IsActive).Select(x => new { x.Id, x.VehicleId, x.DocumentType, DocumentNumber = x.DocumentNumber == null ? null : "****" + x.DocumentNumber.Substring(Math.Max(0, x.DocumentNumber.Length - 4)), x.IssuedAt, x.ExpiresAt, x.Provider, x.IsRequired, x.ConcurrencyToken }).ToListAsync(ct));
    [HttpPost("/api/fleet/vehicles/{vehicleId:guid}/documents"), RequirePermission(FleetPermissions.MaintenanceManageDocuments)] public async Task<ActionResult<ApiResponse<object>>> CreateDocument(Guid vehicleId, FleetVehicleDocument body, CancellationToken ct) { body.Id = Guid.NewGuid(); body.VehicleId = vehicleId; body.CreatedAt = DateTime.UtcNow; body.CreatedByUserId = Actor(); db.Add(body); await db.SaveChangesAsync(ct); return ApiResponse<object>.Ok(new { body.Id, body.ConcurrencyToken }); }
    [HttpPut("/api/fleet/vehicle-documents/{id:guid}"), RequirePermission(FleetPermissions.MaintenanceManageDocuments)] public async Task<ActionResult<ApiResponse<object>>> UpdateDocument(Guid id, FleetVehicleDocument body, CancellationToken ct) { var item = await db.FleetVehicleDocuments.FindAsync([id], ct); if (item is null) return NotFound(); if (item.ConcurrencyToken != body.ConcurrencyToken) return Conflict(ApiResponse<object>.Fail("Concurrency conflict.")); item.DocumentType = body.DocumentType; item.DocumentNumber = body.DocumentNumber?.Trim(); item.IssuedAt = body.IssuedAt; item.ExpiresAt = body.ExpiresAt; item.Provider = body.Provider?.Trim(); item.Notes = body.Notes?.Trim(); item.IsRequired = body.IsRequired; item.UpdatedAt = DateTime.UtcNow; item.UpdatedByUserId = Actor(); item.ConcurrencyToken = Guid.NewGuid(); await db.SaveChangesAsync(ct); return ApiResponse<object>.Ok(new { item.Id, item.ConcurrencyToken }); }
    [HttpPost("/api/fleet/vehicle-documents/{id:guid}/disable"), RequirePermission(FleetPermissions.MaintenanceManageDocuments)] public async Task<ActionResult<ApiResponse<object>>> DisableDocument(Guid id, MaintenanceActionBody body, CancellationToken ct) { var item = await db.FleetVehicleDocuments.FindAsync([id], ct); if (item is null) return NotFound(); if (item.ConcurrencyToken != body.ConcurrencyToken || string.IsNullOrWhiteSpace(body.Reason)) return Conflict(ApiResponse<object>.Fail("Reason and current concurrency token are required.")); item.IsActive = false; item.UpdatedAt = DateTime.UtcNow; item.UpdatedByUserId = Actor(); item.ConcurrencyToken = Guid.NewGuid(); await db.SaveChangesAsync(ct); return ApiResponse<object>.Ok(new { item.Id, item.ConcurrencyToken }); }
    [HttpPost("/api/fleet/maintenance/{id:guid}/attachments"), RequirePermission(FleetPermissions.MaintenanceUploadAttachment)] public async Task<ActionResult<ApiResponse<object>>> Upload(Guid id, IFormFile file, CancellationToken ct) { if (!await db.FleetVehicleMaintenanceRecords.AnyAsync(x => x.Id == id, ct)) return NotFound(); try { var actor = Actor(); var attachment = await storage.Save(id, actor, file, ct); db.Add(attachment); Audit("MaintenanceAttachmentUploaded", attachment.Id, actor); await db.SaveChangesAsync(ct); return ApiResponse<object>.Ok(attachment); } catch (ArgumentException ex) { return BadRequest(ApiResponse<object>.Fail(ex.Message)); } }
    [HttpGet("/api/fleet/maintenance/attachments/{id:guid}"), RequirePermission(FleetPermissions.MaintenanceView)] public async Task<IActionResult> DownloadAttachment(Guid id, CancellationToken ct) { var item = await db.FleetMaintenanceAttachments.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id && !x.IsDeleted, ct); if (item is null) return NotFound(); var file = storage.Get(item); return file.Exists ? PhysicalFile(file.FullName, item.ContentType, item.OriginalFileName) : NotFound(); }
    [HttpDelete("/api/fleet/maintenance/attachments/{id:guid}"), RequirePermission(FleetPermissions.MaintenanceUploadAttachment)] public async Task<ActionResult<ApiResponse<object>>> DeleteAttachment(Guid id, CancellationToken ct) { var item = await db.FleetMaintenanceAttachments.FindAsync([id], ct); if (item is null) return NotFound(); item.IsDeleted = true; item.DeletedAt = DateTime.UtcNow; item.DeletedByUserId = Actor(); Audit("MaintenanceAttachmentDeleted", id, Actor()); await db.SaveChangesAsync(ct); return ApiResponse<object>.Ok(new { item.Id }); }

    private async Task<ActionResult<ApiResponse<object>>> Change(Guid id, string status, string eventType, MaintenanceActionBody body, CancellationToken ct) { var item = await db.FleetVehicleMaintenanceSchedules.FindAsync([id], ct); if (item is null) return NotFound(); if (item.ConcurrencyToken != body.ConcurrencyToken) return Conflict(ApiResponse<object>.Fail("Concurrency conflict.")); if (status == FleetMaintenanceStatuses.Cancelled && string.IsNullOrWhiteSpace(body.Reason)) return BadRequest(ApiResponse<object>.Fail("Reason is required.")); item.Status = status; item.IsActive = status != FleetMaintenanceStatuses.Cancelled; item.UpdatedAt = DateTime.UtcNow; item.UpdatedByUserId = Actor(); item.ConcurrencyToken = Guid.NewGuid(); var actor = Actor(); Audit(eventType, id, actor, body.Reason); await events.PublishAsync(new(eventType, "FLEET", "FleetMaintenance", id, actor, HttpContext.TraceIdentifier, new { item.VehicleId, Reason = body.Reason }, []), ct); await db.SaveChangesAsync(ct); return ApiResponse<object>.Ok(new { item.Id, item.Status, item.ConcurrencyToken }); }
    private Guid Actor() => Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
    private void Audit(string action, Guid id, Guid actor, string? reason = null) => db.AuditLogs.Add(new() { UserId = actor, EffectiveActorUserId = actor, Action = action, EntityName = "FleetMaintenance", EntityId = id.ToString(), Reason = reason?.Trim(), CorrelationId = HttpContext.TraceIdentifier });
}
public sealed record MaintenanceScheduleBody(Guid VehicleId, Guid MaintenanceTypeId, DateTime? DueDate, decimal? DueMileage, int? ReminderDays, decimal? ReminderMileage, int? RecurrenceDays, decimal? RecurrenceMileage, string? Notes, Guid? ConcurrencyToken);
public sealed record MaintenanceActionBody(Guid ConcurrencyToken, string? Reason);
public sealed record MaintenanceStartBody(Guid ConcurrencyToken, DateTime? StartedAt, decimal? StartMileage, string? Vendor, string? Note);
public sealed record MaintenanceCompleteBody(Guid ConcurrencyToken, DateTime? StartedAt, DateTime? CompletedAt, decimal? CompletedMileage, decimal? Cost, string? Vendor, string? InvoiceNumber, string? Description, string? Result, DateTime? NextDueDate, decimal? NextDueMileage, string? OverrideReason);
