using System.Data;
using System.Security.Claims;
using Hop.Api.Authorization;
using Hop.Api.Data;
using Hop.Api.DTOs;
using Hop.Api.Models;
using Hop.Api.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Hop.Api.Controllers;

public sealed record EmergencyRequestCreate(string Purpose,string MissionType,Guid? RequestedVehicleTypeId,string Destination,string ContactName,string ContactPhone,string IncidentLocation,DateTime RequestedDepartureAt,DateTime ExpectedReturnAt,int PassengerCount,string EmergencyReason,string? SpecialRequirement,string EmergencyPolicyCode);
public sealed record EmergencyDispatchRequest(Guid VehicleId,Guid DriverUserId,Guid ConcurrencyToken,string Reason);
public sealed record EmergencyBypassRequest(Guid ConcurrencyToken,string Reason);
public sealed record EmergencyReviewRequest(Guid ConcurrencyToken,string Outcome,bool WasBypassAppropriate,string? ResponseTimeAssessment,string? SafetyIssues,string? FollowUpActions,string? Notes);

[ApiController,Authorize,Route("api/fleet/emergency-requests")]
public sealed class FleetEmergencyController(AppDbContext db,FleetRequestNumberService numbers,FleetAvailabilityService availability,IWorkflowPermissionValidator permissions,IDomainEventPublisher events) : ControllerBase
{
    [HttpPost,RequirePermission(FleetPermissions.EmergencyCreate)]
    public async Task<ActionResult<ApiResponse<object>>> Create(EmergencyRequestCreate r,CancellationToken ct)
    {
        if(string.IsNullOrWhiteSpace(r.EmergencyReason)||string.IsNullOrWhiteSpace(r.ContactName)||string.IsNullOrWhiteSpace(r.ContactPhone)||string.IsNullOrWhiteSpace(r.IncidentLocation))return BadRequest(ApiResponse<object>.Fail("Emergency reason, reporter contact and incident location are required."));
        if(r.ExpectedReturnAt<=r.RequestedDepartureAt||r.PassengerCount<1)return BadRequest(ApiResponse<object>.Fail("Invalid trip time or passenger count."));
        var actor=Actor();await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var now=DateTime.UtcNow;
        var requestedCode=r.EmergencyPolicyCode.Trim();var policy=await db.FleetEmergencyPolicies.AsNoTracking().Where(x=>x.Code==requestedCode&&x.Priority==FleetPriorities.Emergency&&x.IsActive&&x.EffectiveFrom<=now&&(x.EffectiveTo==null||x.EffectiveTo>now)).OrderByDescending(x=>x.EffectiveFrom).FirstOrDefaultAsync(ct);
        var item=new FleetRequest{RequestNo=await numbers.GenerateAsync(now,ct),RequesterUserId=actor,RequesterDepartmentId=await db.Users.Where(x=>x.Id==actor).Select(x=>x.DepartmentId).SingleAsync(ct),RequestDate=DateOnly.FromDateTime(now),Purpose=r.Purpose.Trim(),MissionType=r.MissionType.Trim(),RequestedVehicleTypeId=r.RequestedVehicleTypeId,Destination=r.Destination.Trim(),ContactPersonName=r.ContactName.Trim(),ContactPhone=r.ContactPhone.Trim(),DepartureAt=r.RequestedDepartureAt,RequestedDepartureAt=r.RequestedDepartureAt,ExpectedReturnAt=r.ExpectedReturnAt,PassengerCount=r.PassengerCount,SpecialRequirement=r.SpecialRequirement?.Trim(),IsUrgent=true,UrgentReason=r.EmergencyReason.Trim(),Priority=FleetPriorities.Emergency,EmergencyReason=r.EmergencyReason.Trim(),ReportedByUserId=actor,ReportedAt=now,IncidentLocation=r.IncidentLocation.Trim(),EmergencyPolicyCode=policy?.Code??"CONFIG_FALLBACK",EmergencyPolicyId=policy?.Id,ResponseTargetMinutesSnapshot=policy?.ResponseTargetMinutes??15,DispatchTargetMinutesSnapshot=policy?.DispatchTargetMinutes??15,DriverAcknowledgementTargetMinutesSnapshot=policy?.DriverAcknowledgementTargetMinutes??15,ApprovalBypassAllowedSnapshot=policy?.ApprovalBypassAllowed??true,PostReviewRequiredSnapshot=policy?.PostReviewRequired??true,RequiresPostReview=policy?.PostReviewRequired??true,EmergencyDeclaredByUserId=actor,EmergencyDeclaredAt=now,Status=FleetRequestStatuses.Draft,CreatedByUserId=actor};db.Add(item);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return ApiResponse<object>.Ok(ToSafe(item));
    }
    [HttpPost("{id:guid}/submit"),RequirePermission(FleetPermissions.EmergencyCreate)] public async Task<ActionResult<ApiResponse<object>>> Submit(Guid id,FleetWorkflowActionRequest r,CancellationToken ct){var x=await Owned(id,ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Emergency request not found."));if(x.Status!=FleetRequestStatuses.Draft||x.ConcurrencyToken!=r.ConcurrencyToken)return Conflict(ApiResponse<object>.Fail("Emergency request changed or is not draft."));var from=x.Status;x.Status=FleetRequestStatuses.PendingDispatch;x.SubmittedAt=DateTime.UtcNow;x.ConcurrencyToken=Guid.NewGuid();History(x,from,x.Status,"FleetEmergency.Submitted",r.Reason);await Publish("FleetEmergency.Submitted",x,ct);await db.SaveChangesAsync(ct);return ApiResponse<object>.Ok(ToSafe(x));}
    [HttpGet("queue"),RequirePermission(FleetPermissions.EmergencyViewQueue)] public async Task<ActionResult<ApiResponse<object>>> Queue([FromQuery]string? priority,[FromQuery]int page=1,[FromQuery]int pageSize=25,CancellationToken ct=default){page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,100);var q=db.FleetRequests.AsNoTracking().Where(x=>x.Status==FleetRequestStatuses.PendingDispatch||x.Status==FleetRequestStatuses.PendingAdminReview||x.Status==FleetRequestStatuses.PendingDirector);if(!string.IsNullOrWhiteSpace(priority))q=q.Where(x=>x.Priority==priority);var total=await q.CountAsync(ct);var rows=await q.OrderBy(x=>x.Priority==FleetPriorities.Emergency?0:x.Priority==FleetPriorities.Urgent?1:2).ThenBy(x=>x.SubmittedAt).Skip((page-1)*pageSize).Take(pageSize).Select(x=>new{x.Id,x.RequestNo,x.Priority,x.Status,x.Destination,x.SubmittedAt,ResponseTargetMinutes=x.ResponseTargetMinutesSnapshot??(x.Priority==FleetPriorities.Emergency?15:x.Priority==FleetPriorities.Urgent?60:240),x.EmergencyPolicyCode}).ToListAsync(ct);var now=DateTime.UtcNow;var items=rows.Select(x=>new{x.Id,x.RequestNo,x.Priority,x.Status,x.Destination,x.SubmittedAt,ElapsedSeconds=x.SubmittedAt is null?0:(long)(now-x.SubmittedAt.Value).TotalSeconds,x.ResponseTargetMinutes,x.EmergencyPolicyCode,SlaBreached=x.SubmittedAt!=null&&now>x.SubmittedAt.Value.AddMinutes(x.ResponseTargetMinutes)});return ApiResponse<object>.Ok(new{items,total,page,pageSize});}
    [HttpGet("{id:guid}"),RequirePermission(FleetPermissions.EmergencyViewOwn)] public async Task<ActionResult<ApiResponse<object>>> Detail(Guid id,CancellationToken ct){var x=await db.FleetRequests.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&x.Priority==FleetPriorities.Emergency,ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Emergency request not found."));if(x.RequesterUserId!=Actor()&&!await permissions.HasAsync(Actor(),FleetPermissions.EmergencyViewQueue,ct))return Forbid();return ApiResponse<object>.Ok(ToSafe(x));}
    [HttpPost("{id:guid}/dispatch"),RequirePermission(FleetPermissions.EmergencyDispatch)] public async Task<ActionResult<ApiResponse<object>>> Dispatch(Guid id,EmergencyDispatchRequest r,CancellationToken ct){await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var x=await db.FleetRequests.Include(x=>x.Assignments).SingleOrDefaultAsync(x=>x.Id==id&&x.Priority==FleetPriorities.Emergency,ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Emergency request not found."));if(x.Status!=FleetRequestStatuses.PendingDispatch||x.ConcurrencyToken!=r.ConcurrencyToken)return Conflict(ApiResponse<object>.Fail("Emergency request changed or is not pending dispatch."));foreach(var key in new[]{r.VehicleId,r.DriverUserId}.OrderBy(x=>x))await db.Database.ExecuteSqlInterpolatedAsync($"SELECT pg_advisory_xact_lock(hashtext({key.ToString()}))",ct);var a=await availability.GetAsync(x,ct);var vehicle=a.Vehicles.SingleOrDefault(v=>v.Id==r.VehicleId);var driver=a.Drivers.SingleOrDefault(v=>v.Id==r.DriverUserId);if(vehicle?.IsAvailable!=true||driver?.IsAvailable!=true)return Conflict(ApiResponse<object>.Fail($"Safety/availability block: {string.Join(", ",(vehicle?.Reasons??[]).Concat(driver?.Reasons??[]))}"));var actor=Actor();db.Add(new FleetAssignment{FleetRequestId=x.Id,VehicleId=r.VehicleId,DriverUserId=r.DriverUserId,AssignedByUserId=actor,AssignmentReason=r.Reason.Trim()});var from=x.Status;x.Status=FleetRequestStatuses.PendingAdminReview;x.ConcurrencyToken=Guid.NewGuid();History(x,from,x.Status,"FleetEmergency.Assigned",r.Reason);await Publish("FleetEmergency.Assigned",x,ct);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return ApiResponse<object>.Ok(ToSafe(x));}
    [HttpPost("{id:guid}/bypass-approval"),RequirePermission(FleetPermissions.EmergencyBypassApproval)] public async Task<ActionResult<ApiResponse<object>>> Bypass(Guid id,EmergencyBypassRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))return BadRequest(ApiResponse<object>.Fail("Bypass reason is required."));var x=await db.FleetRequests.Include(x=>x.Assignments).SingleOrDefaultAsync(x=>x.Id==id&&x.Priority==FleetPriorities.Emergency,ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Emergency request not found."));if(x.Status!=FleetRequestStatuses.PendingAdminReview||x.ConcurrencyToken!=r.ConcurrencyToken||!x.Assignments.Any(a=>a.IsActive))return Conflict(ApiResponse<object>.Fail("Emergency request changed or has no active safe assignment."));var active=x.Assignments.Single(a=>a.IsActive);var safety=await availability.GetAsync(x,ct);if(safety.Vehicles.Single(v=>v.Id==active.VehicleId).IsAvailable!=true||safety.Drivers.Single(v=>v.Id==active.DriverUserId).IsAvailable!=true)return Conflict(ApiResponse<object>.Fail("Safety validation cannot be bypassed."));var from=x.Status;x.Status=FleetRequestStatuses.PendingDriverAck;x.ConcurrencyToken=Guid.NewGuid();History(x,from,x.Status,"FleetEmergency.ApprovalBypassed",r.Reason);Audit(x,"FleetEmergency.ApprovalBypassed",r.Reason);await Publish("FleetEmergency.ApprovalBypassed",x,ct);await db.SaveChangesAsync(ct);return ApiResponse<object>.Ok(ToSafe(x));}
    [HttpPost("{id:guid}/post-review"),RequirePermission(FleetPermissions.EmergencyReview)] public async Task<ActionResult<ApiResponse<object>>> Review(Guid id,EmergencyReviewRequest r,CancellationToken ct){if(!FleetEmergencyReviewOutcomes.All.Contains(r.Outcome))return BadRequest(ApiResponse<object>.Fail("Invalid review outcome."));var x=await db.FleetRequests.SingleOrDefaultAsync(x=>x.Id==id&&x.Priority==FleetPriorities.Emergency,ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Emergency request not found."));if(x.ConcurrencyToken!=r.ConcurrencyToken||x.Status!=FleetRequestStatuses.Completed||!x.RequiresPostReview)return Conflict(ApiResponse<object>.Fail("Post-review is not available."));if(await db.FleetEmergencyPostReviews.AnyAsync(y=>y.FleetRequestId==id,ct))return Conflict(ApiResponse<object>.Fail("Post-review already exists."));var review=new FleetEmergencyPostReview{FleetRequestId=id,ReviewedByUserId=Actor(),Outcome=r.Outcome,WasBypassAppropriate=r.WasBypassAppropriate,ResponseTimeAssessment=r.ResponseTimeAssessment?.Trim(),SafetyIssues=r.SafetyIssues?.Trim(),FollowUpActions=r.FollowUpActions?.Trim(),Notes=r.Notes?.Trim()};db.Add(review);x.RequiresPostReview=false;x.ConcurrencyToken=Guid.NewGuid();History(x,x.Status,x.Status,"FleetEmergency.PostReviewCompleted",r.Notes);Audit(x,"FleetEmergency.PostReviewCompleted",r.Outcome);await Publish("FleetEmergency.PostReviewCompleted",x,ct);await db.SaveChangesAsync(ct);return ApiResponse<object>.Ok(new{review.Id,review.Outcome,x.ConcurrencyToken});}
    private async Task<FleetRequest?> Owned(Guid id,CancellationToken ct){var actor=Actor();return await db.FleetRequests.Include(x=>x.StatusHistories).SingleOrDefaultAsync(x=>x.Id==id&&x.Priority==FleetPriorities.Emergency&&x.RequesterUserId==actor,ct);} private Guid Actor()=>Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
    private void History(FleetRequest x,string from,string to,string action,string? reason)=>x.StatusHistories.Add(new(){FromStatus=from,ToStatus=to,Action=action,ActorUserId=Actor(),Reason=reason?.Trim(),CorrelationId=HttpContext.TraceIdentifier});
    private void Audit(FleetRequest x,string action,string detail)=>db.AuditLogs.Add(new(){UserId=Actor(),EffectiveActorUserId=Actor(),Action=action,EntityName="FleetRequest",EntityId=x.Id.ToString(),Detail=detail,CorrelationId=HttpContext.TraceIdentifier});
    private Task Publish(string type,FleetRequest x,CancellationToken ct)=>events.PublishAsync(new(type,"FLEET","FleetRequest",x.Id,Actor(),HttpContext.TraceIdentifier,new{x.Id,x.RequestNo,x.Priority,x.Status},[]),ct);
    private static object ToSafe(FleetRequest x)=>new{x.Id,x.RequestNo,x.Priority,x.Status,x.Purpose,x.Destination,x.IncidentLocation,x.DepartureAt,x.ExpectedReturnAt,x.PassengerCount,ContactPhone=Mask(x.ContactPhone),x.EmergencyReason,x.RequiresPostReview,x.ConcurrencyToken};
    private static string Mask(string value)=>value.Length<=4?new string('*',value.Length):new string('*',value.Length-4)+value[^4..];
}
