using Hop.Api.Authorization;
using Hop.Api.Data;
using Hop.Api.DTOs;
using Hop.Api.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Hop.Api.Controllers;

[ApiController, Authorize, Route("api/fleet/calendar")]
public sealed class FleetCalendarController(AppDbContext db, FleetDateRangeService ranges) : ControllerBase
{
    [HttpGet]
    [RequirePermission(FleetPermissions.CalendarView)]
    public async Task<ActionResult<ApiResponse<object>>> Get([FromQuery] DateOnly? start, [FromQuery] DateOnly? end, [FromQuery] string? eventTypes, [FromQuery] Guid? vehicleId, [FromQuery] Guid? driverUserId, [FromQuery] Guid? departmentId, [FromQuery] string? statuses, [FromQuery] bool includeCancelled = false, CancellationToken ct = default)
    {
        if (start is null || end is null) return BadRequest(ApiResponse<object>.Fail("start and end are required."));
        FleetUtcRange range; try { range = ranges.Resolve("custom", start, end, true); } catch (ArgumentException ex) { return BadRequest(ApiResponse<object>.Fail(ex.Message)); }
        var types = Split(eventTypes); var statusFilter = Split(statuses); var now = DateTime.UtcNow; var all = new List<CalendarEventDto>();
        bool Include(string value) => types.Count == 0 || types.Contains(value);

        var requests = db.FleetRequests.AsNoTracking().Where(x => x.DepartureAt < range.End && x.ExpectedReturnAt > range.Start && (includeCancelled || x.Status != "CANCELLED"));
        if (departmentId != null) requests = requests.Where(x => x.RequesterDepartmentId == departmentId); if (vehicleId != null) requests = requests.Where(x => x.Assignments.Any(a => a.VehicleId == vehicleId)); if (driverUserId != null) requests = requests.Where(x => x.Assignments.Any(a => a.DriverUserId == driverUserId)); if (statusFilter.Count > 0) requests = requests.Where(x => statusFilter.Contains(x.Status));
        if (Include("REQUEST")) all.AddRange(await requests.Select(x => new CalendarEventDto("request:"+x.Id,"REQUEST",(x.Priority=="EMERGENCY"?"[EMERGENCY] ":x.Priority=="URGENT"?"[URGENT] ":"")+x.RequestNo+" · "+x.Destination,x.DepartureAt,x.ExpectedReturnAt,false,x.Status,x.Priority=="EMERGENCY"?"danger":x.IsUrgent?"warning":"info",x.Id,null,null,x.Assignments.Where(a=>a.IsActive).Select(a=>(Guid?)a.VehicleId).FirstOrDefault(),x.Assignments.Where(a=>a.IsActive).Select(a=>(Guid?)a.DriverUserId).FirstOrDefault(),null,null,"/fleet/requests/"+x.Id,new { x.RequestNo,x.Priority, Department=x.RequesterDepartment!=null?x.RequesterDepartment.Name:null, x.Destination, x.PassengerCount })).ToListAsync(ct));

        if (Include("ASSIGNMENT")) { var q=db.FleetAssignments.AsNoTracking().Where(a=>a.FleetRequest!.DepartureAt<range.End&&a.FleetRequest.ExpectedReturnAt>range.Start); if(vehicleId!=null)q=q.Where(a=>a.VehicleId==vehicleId);if(driverUserId!=null)q=q.Where(a=>a.DriverUserId==driverUserId);if(departmentId!=null)q=q.Where(a=>a.FleetRequest!.RequesterDepartmentId==departmentId); all.AddRange(await q.Select(a=>new CalendarEventDto("assignment:"+a.Id,"ASSIGNMENT",a.Vehicle!.VehicleCode+" · "+a.DriverUser!.FullName,a.FleetRequest!.DepartureAt,db.FleetAssignments.Where(n=>n.ReplacedAssignmentId==a.Id).Select(n=>n.AssignedAt).FirstOrDefault()==default?a.FleetRequest.ExpectedReturnAt:db.FleetAssignments.Where(n=>n.ReplacedAssignmentId==a.Id).Select(n=>n.AssignedAt).First(),false,a.AssignmentStatus,a.IsActive?"info":"muted",a.FleetRequestId,a.Id,null,a.VehicleId,a.DriverUserId,null,null,"/fleet/requests/"+a.FleetRequestId,new { a.IsActive,a.ReplacedAssignmentId,a.AssignedAt })).ToListAsync(ct)); }

        if (Include("TRIP")) { var q=db.FleetTripRecords.AsNoTracking().Where(t=>t.ActualStartAt<range.End&&(t.ActualEndAt??t.AbortedAt??now)>range.Start); if(vehicleId!=null)q=q.Where(t=>t.Assignment!.VehicleId==vehicleId);if(driverUserId!=null)q=q.Where(t=>t.DriverUserId==driverUserId); all.AddRange(await q.Select(t=>new CalendarEventDto("trip:"+t.Id,"TRIP","Trip · "+t.FleetRequest!.RequestNo,t.ActualStartAt!.Value,t.ActualEndAt??t.AbortedAt??now,false,t.IsAborted?"ABORTED":t.ActualEndAt!=null?"COMPLETED":"IN_PROGRESS",t.IsAborted?"danger":"success",t.FleetRequestId,t.AssignmentId,t.Id,t.Assignment!.VehicleId,t.DriverUserId,null,null,"/fleet/requests/"+t.FleetRequestId,new { t.StartMileage,t.EndMileage })).ToListAsync(ct)); }

        if (Include("VEHICLE_UNAVAILABILITY")) { var q=db.FleetVehicleUnavailability.AsNoTracking().Where(x=>x.StartAt<range.End&&x.EndAt>range.Start);if(vehicleId!=null)q=q.Where(x=>x.VehicleId==vehicleId);all.AddRange(await q.Select(x=>new CalendarEventDto("vehicle-unavailability:"+x.Id,"VEHICLE_UNAVAILABILITY",x.Vehicle!.VehicleCode+" · "+x.Reason,x.StartAt,x.EndAt,false,x.Type,"warning",null,null,null,x.VehicleId,null,null,null,"/fleet/calendar",new { x.Reason,x.Type })).ToListAsync(ct)); }
        if (Include("DRIVER_UNAVAILABILITY")) { var q=db.FleetDriverUnavailability.AsNoTracking().Where(x=>x.StartAt<range.End&&x.EndAt>range.Start);if(driverUserId!=null)q=q.Where(x=>x.UserId==driverUserId);all.AddRange(await q.Select(x=>new CalendarEventDto("driver-unavailability:"+x.Id,"DRIVER_UNAVAILABILITY",x.User!.FullName+" · ไม่พร้อมใช้งาน",x.StartAt,x.EndAt,false,"UNAVAILABLE","warning",null,null,null,null,x.UserId,null,null,"/fleet/calendar",new { x.Reason })).ToListAsync(ct)); }
        if (Include("MAINTENANCE")) { var q=db.FleetVehicleMaintenanceSchedules.AsNoTracking().Where(x=>x.IsActive&&((x.DueDate>=range.Start&&x.DueDate<range.End)||(x.Status=="IN_PROGRESS"&&x.UpdatedAt<range.End)));if(vehicleId!=null)q=q.Where(x=>x.VehicleId==vehicleId);all.AddRange(await q.Select(x=>new CalendarEventDto("maintenance:"+x.Id,"MAINTENANCE",x.MaintenanceType!.Name,x.Status=="IN_PROGRESS"?(x.UpdatedAt??x.CreatedAt):x.DueDate!.Value,x.Status=="IN_PROGRESS"?now:(x.DueDate!.Value.AddHours(1)),false,x.Status,(x.DueDate<now||x.DueMileage<x.Vehicle!.CurrentMileage)?"danger":"warning",null,null,null,x.VehicleId,null,x.Id,null,"/fleet/maintenance/"+x.Id,new { Blocking=x.MaintenanceType.BlocksAvailabilityWhenOverdue,x.DueDate,x.DueMileage })).ToListAsync(ct)); }
        if (Include("VEHICLE_DOCUMENT_EXPIRY")) { var q=db.FleetVehicleDocuments.AsNoTracking().Where(x=>x.IsActive&&x.ExpiresAt>=range.Start&&x.ExpiresAt<range.End);if(vehicleId!=null)q=q.Where(x=>x.VehicleId==vehicleId);all.AddRange(await q.Select(x=>new CalendarEventDto("document:"+x.Id,"VEHICLE_DOCUMENT_EXPIRY",x.DocumentType,x.ExpiresAt!.Value,x.ExpiresAt.Value,true,"EXPIRING",x.ExpiresAt<now?"danger":"warning",null,null,null,x.VehicleId,null,null,null,"/fleet/vehicles/"+x.VehicleId+"/documents",new { x.DocumentType })).ToListAsync(ct)); }
        if (Include("CANCELLATION_REQUEST")) { var q=db.FleetCancellationRequests.AsNoTracking().Where(x=>x.CreatedAt<range.End&&(x.CompletedAt??x.ReviewedAt??now)>range.Start);if(departmentId!=null)q=q.Where(x=>x.FleetRequest!.RequesterDepartmentId==departmentId);all.AddRange(await q.Select(x=>new CalendarEventDto("cancellation:"+x.Id,"CANCELLATION_REQUEST","Cancellation · "+x.FleetRequest!.RequestNo,x.CreatedAt,x.CompletedAt??x.ReviewedAt??x.CreatedAt.AddMinutes(1),false,x.Status,x.Status=="PENDING"?"warning":"muted",x.FleetRequestId,null,null,x.FleetRequest.Assignments.Where(a=>a.IsActive).Select(a=>(Guid?)a.VehicleId).FirstOrDefault(),null,null,x.Id,"/fleet/requests/"+x.FleetRequestId,new { RequestedBy=x.RequestedByUser!.FullName,x.ReviewReason })).ToListAsync(ct)); }
        return ApiResponse<object>.Ok(all.OrderBy(x=>x.StartAt).ToList());
    }
    private static HashSet<string> Split(string? value)=>string.IsNullOrWhiteSpace(value)?new(StringComparer.OrdinalIgnoreCase):value.Split(',',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).ToHashSet(StringComparer.OrdinalIgnoreCase);
}
public sealed record CalendarEventDto(string Id,string EventType,string Title,DateTime StartAt,DateTime EndAt,bool IsAllDay,string Status,string Severity,Guid? RequestId,Guid? AssignmentId,Guid? TripId,Guid? VehicleId,Guid? DriverUserId,Guid? MaintenanceId,Guid? CancellationRequestId,string DetailUrl,object Metadata);
