using System.Security.Claims;
using System.Text.Json;
using Hop.Api.Authorization;
using Hop.Api.Data;
using Hop.Api.DTOs;
using Hop.Api.Models;
using Hop.Api.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Hop.Api.Controllers;

public sealed record CapabilitySave(string Code,string Name,string? Description,string Category,string DataType,string? Unit,decimal? MinimumNumericValue,decimal? MaximumNumericValue,string? EnumOptionsJson,bool IsRequiredSafetyCapability,bool IsActive,int SortOrder,Guid? ConcurrencyToken);
public sealed record TypedCapabilityValue(Guid CapabilityId,bool? BooleanValue,decimal? NumericValue,string? TextValue,string? EnumValue,DateTime? EffectiveFrom,DateTime? EffectiveTo,bool IsActive=true,Guid? ConcurrencyToken=null);
public sealed record RequiredCapabilityValue(Guid CapabilityId,string Operator,bool? RequiredBooleanValue,decimal? RequiredNumericValue,string? RequiredTextValue,string? RequiredEnumValue,bool IsMandatory,string? Notes);
public sealed record CompatibilityOverrideRequest(Guid VehicleId,Guid? AssignmentId,Guid[] CapabilityIds,string Reason,Guid RequestConcurrencyToken);

[ApiController,Authorize,Route("api/fleet/capabilities")]
public sealed class FleetCapabilitiesController(AppDbContext db) : ControllerBase
{
    [HttpGet,RequirePermission(FleetPermissions.CapabilityView)]
    public async Task<ActionResult<ApiResponse<object>>> List([FromQuery]string? search,[FromQuery]string? category,[FromQuery]string? dataType,[FromQuery]bool? active,[FromQuery]string sort="sortOrder",[FromQuery]int page=1,[FromQuery]int pageSize=25,CancellationToken ct=default)
    { page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,100);var q=db.FleetCapabilities.AsNoTracking();if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.Code.Contains(search)||x.Name.Contains(search));if(!string.IsNullOrWhiteSpace(category))q=q.Where(x=>x.Category==category);if(!string.IsNullOrWhiteSpace(dataType))q=q.Where(x=>x.DataType==dataType);if(active.HasValue)q=q.Where(x=>x.IsActive==active);q=sort=="code"?q.OrderBy(x=>x.Code):sort=="name"?q.OrderBy(x=>x.Name):q.OrderBy(x=>x.SortOrder).ThenBy(x=>x.Code);var total=await q.CountAsync(ct);var items=await q.Skip((page-1)*pageSize).Take(pageSize).ToListAsync(ct);return ApiResponse<object>.Ok(new{items,total,page,pageSize}); }
    [HttpGet("{id:guid}"),RequirePermission(FleetPermissions.CapabilityView)] public async Task<ActionResult<ApiResponse<object>>> Detail(Guid id,CancellationToken ct){var x=await db.FleetCapabilities.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Capability not found."));var vehicleCount=await db.FleetVehicleCapabilities.CountAsync(v=>v.CapabilityId==id&&v.IsActive,ct);var requestCount=await db.FleetRequestRequiredCapabilities.CountAsync(v=>v.CapabilityId==id,ct);return ApiResponse<object>.Ok(new{x,vehicleCount,requestCount});}
    [HttpPost,RequirePermission(FleetPermissions.CapabilityManage)] public async Task<ActionResult<ApiResponse<FleetCapability>>> Create(CapabilitySave r,CancellationToken ct){var error=Validate(r);if(error is not null)return BadRequest(ApiResponse<FleetCapability>.Fail(error));if(await db.FleetCapabilities.AnyAsync(x=>x.Code==r.Code.Trim(),ct))return Conflict(ApiResponse<FleetCapability>.Fail("Capability code already exists."));var x=new FleetCapability{Code=r.Code.Trim(),Name=r.Name.Trim(),Description=r.Description?.Trim(),Category=r.Category.Trim(),DataType=r.DataType,Unit=r.DataType==FleetCapabilityDataTypes.Boolean?null:r.Unit?.Trim(),MinimumNumericValue=r.MinimumNumericValue,MaximumNumericValue=r.MaximumNumericValue,EnumOptionsJson=r.EnumOptionsJson,IsRequiredSafetyCapability=r.IsRequiredSafetyCapability,IsActive=r.IsActive,SortOrder=r.SortOrder,CreatedByUserId=Actor()};db.Add(x);await db.SaveChangesAsync(ct);return ApiResponse<FleetCapability>.Ok(x);}
    [HttpPut("{id:guid}"),RequirePermission(FleetPermissions.CapabilityManage)] public async Task<ActionResult<ApiResponse<FleetCapability>>> Update(Guid id,CapabilitySave r,CancellationToken ct){var x=await db.FleetCapabilities.FindAsync([id],ct);if(x is null)return NotFound(ApiResponse<FleetCapability>.Fail("Capability not found."));if(r.ConcurrencyToken!=x.ConcurrencyToken)return Conflict(ApiResponse<FleetCapability>.Fail("Capability changed."));var error=Validate(r);if(error is not null)return BadRequest(ApiResponse<FleetCapability>.Fail(error));if(x.DataType!=r.DataType&&await db.FleetVehicleCapabilities.AnyAsync(v=>v.CapabilityId==id,ct))return Conflict(ApiResponse<FleetCapability>.Fail("Data type cannot change while history exists."));x.Name=r.Name.Trim();x.Description=r.Description?.Trim();x.Category=r.Category.Trim();x.DataType=r.DataType;x.Unit=r.DataType==FleetCapabilityDataTypes.Boolean?null:r.Unit?.Trim();x.MinimumNumericValue=r.MinimumNumericValue;x.MaximumNumericValue=r.MaximumNumericValue;x.EnumOptionsJson=r.EnumOptionsJson;x.IsRequiredSafetyCapability=r.IsRequiredSafetyCapability;x.IsActive=r.IsActive;x.SortOrder=r.SortOrder;x.UpdatedAt=DateTime.UtcNow;x.UpdatedByUserId=Actor();x.ConcurrencyToken=Guid.NewGuid();await db.SaveChangesAsync(ct);return ApiResponse<FleetCapability>.Ok(x);}
    [HttpPost("{id:guid}/disable"),RequirePermission(FleetPermissions.CapabilityManage)] public async Task<ActionResult<ApiResponse<object>>> Disable(Guid id,[FromBody]FleetWorkflowActionRequest r,CancellationToken ct){var x=await db.FleetCapabilities.FindAsync([id],ct);if(x is null)return NotFound(ApiResponse<object>.Fail("Capability not found."));if(x.ConcurrencyToken!=r.ConcurrencyToken)return Conflict(ApiResponse<object>.Fail("Capability changed."));x.IsActive=false;x.UpdatedAt=DateTime.UtcNow;x.UpdatedByUserId=Actor();x.ConcurrencyToken=Guid.NewGuid();await db.SaveChangesAsync(ct);return ApiResponse<object>.Ok(new{x.Id,x.ConcurrencyToken});}
    private Guid Actor()=>Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
    private static string? Validate(CapabilitySave r){if(string.IsNullOrWhiteSpace(r.Code)||string.IsNullOrWhiteSpace(r.Name)||string.IsNullOrWhiteSpace(r.Category))return "Code, name and category are required.";if(!FleetCapabilityDataTypes.All.Contains(r.DataType))return "Invalid data type.";if(r.MinimumNumericValue>r.MaximumNumericValue)return "Minimum cannot exceed maximum.";if(r.DataType==FleetCapabilityDataTypes.Enum){try{if(JsonSerializer.Deserialize<string[]>(r.EnumOptionsJson??"[]")?.Length<1)return "Enum options are required.";}catch(JsonException){return "Enum options must be valid JSON.";}}return null;}
}

[ApiController,Authorize,Route("api/fleet")]
public sealed class FleetCompatibilityController(AppDbContext db,IFleetCompatibilityService compatibility,IDomainEventPublisher events) : ControllerBase
{
    [HttpGet("vehicles/{vehicleId:guid}/capabilities"),RequirePermission(FleetPermissions.CapabilityView)] public async Task<ActionResult<ApiResponse<object>>> VehicleValues(Guid vehicleId,CancellationToken ct)=>ApiResponse<object>.Ok(await db.FleetVehicleCapabilities.AsNoTracking().Include(x=>x.Capability).Where(x=>x.VehicleId==vehicleId).OrderByDescending(x=>x.EffectiveFrom).ToListAsync(ct));
    [HttpPut("vehicles/{vehicleId:guid}/capabilities"),RequirePermission(FleetPermissions.VehicleCapabilityManage)] public async Task<ActionResult<ApiResponse<object>>> SaveVehicleValues(Guid vehicleId,IReadOnlyList<TypedCapabilityValue> rows,CancellationToken ct){if(!await db.FleetVehicles.AnyAsync(x=>x.Id==vehicleId,ct))return NotFound(ApiResponse<object>.Fail("Vehicle not found."));var actor=Actor();var now=DateTime.UtcNow;foreach(var row in rows){var cap=await db.FleetCapabilities.FindAsync([row.CapabilityId],ct);if(cap is null||!cap.IsActive)return BadRequest(ApiResponse<object>.Fail("Unknown or inactive capability."));compatibility.ValidateValue(cap.DataType,FleetCapabilityOperators.Equals,row.BooleanValue,row.NumericValue,row.TextValue,row.EnumValue);if(row.EffectiveTo<=row.EffectiveFrom)return BadRequest(ApiResponse<object>.Fail("EffectiveTo must be after EffectiveFrom."));var current=await db.FleetVehicleCapabilities.SingleOrDefaultAsync(x=>x.VehicleId==vehicleId&&x.CapabilityId==row.CapabilityId&&x.IsActive&&x.EffectiveTo==null,ct);if(current is not null){if(row.ConcurrencyToken!=current.ConcurrencyToken)return Conflict(ApiResponse<object>.Fail("Vehicle capability changed."));current.IsActive=false;current.EffectiveTo=now;current.ConcurrencyToken=Guid.NewGuid();}db.FleetVehicleCapabilities.Add(new(){VehicleId=vehicleId,CapabilityId=row.CapabilityId,BooleanValue=row.BooleanValue,NumericValue=row.NumericValue,TextValue=row.TextValue?.Trim(),EnumValue=row.EnumValue?.Trim(),EffectiveFrom=row.EffectiveFrom??now,EffectiveTo=row.EffectiveTo,IsActive=row.IsActive,CreatedByUserId=actor});}await db.SaveChangesAsync(ct);return ApiResponse<object>.Ok(new{count=rows.Count});}
    [HttpGet("requests/{requestId:guid}/required-capabilities"),RequirePermission(FleetPermissions.CompatibilityView)] public async Task<ActionResult<ApiResponse<object>>> Requirements(Guid requestId,CancellationToken ct)=>ApiResponse<object>.Ok(await db.FleetRequestRequiredCapabilities.AsNoTracking().Include(x=>x.Capability).Where(x=>x.FleetRequestId==requestId).ToListAsync(ct));
    [HttpPut("requests/{requestId:guid}/required-capabilities"),RequirePermission(FleetPermissions.RequestCapabilityManageOwn)] public async Task<ActionResult<ApiResponse<object>>> SaveRequirements(Guid requestId,IReadOnlyList<RequiredCapabilityValue> rows,CancellationToken ct){var actor=Actor();var request=await db.FleetRequests.Include(x=>x.RequiredCapabilities).SingleOrDefaultAsync(x=>x.Id==requestId,ct);if(request is null)return NotFound(ApiResponse<object>.Fail("Request not found."));if(request.RequesterUserId!=actor||request.Status!=FleetRequestStatuses.Draft)return Forbid();db.RemoveRange(request.RequiredCapabilities);foreach(var row in rows){var cap=await db.FleetCapabilities.FindAsync([row.CapabilityId],ct);if(cap is null||!cap.IsActive)return BadRequest(ApiResponse<object>.Fail("Unknown or inactive capability."));compatibility.ValidateValue(cap.DataType,row.Operator,row.RequiredBooleanValue,row.RequiredNumericValue,row.RequiredTextValue,row.RequiredEnumValue);request.RequiredCapabilities.Add(new(){CapabilityId=row.CapabilityId,Operator=row.Operator,RequiredBooleanValue=row.RequiredBooleanValue,RequiredNumericValue=row.RequiredNumericValue,RequiredTextValue=row.RequiredTextValue?.Trim(),RequiredEnumValue=row.RequiredEnumValue?.Trim(),IsMandatory=row.IsMandatory,Notes=row.Notes?.Trim()});}request.ConcurrencyToken=Guid.NewGuid();await db.SaveChangesAsync(ct);return ApiResponse<object>.Ok(new{count=rows.Count,request.ConcurrencyToken});}
    [HttpGet("requests/{requestId:guid}/compatibility"),RequirePermission(FleetPermissions.CompatibilityView)] public async Task<ActionResult<ApiResponse<object>>> Results(Guid requestId,[FromQuery]Guid? vehicleId,CancellationToken ct){var vehicles=vehicleId.HasValue?[vehicleId.Value]:await db.FleetVehicles.AsNoTracking().Where(x=>x.IsActive).Select(x=>x.Id).ToArrayAsync(ct);var results=new List<FleetCompatibilityResult>();foreach(var id in vehicles)results.Add(await compatibility.EvaluateAsync(requestId,id,DateTime.UtcNow,ct));return ApiResponse<object>.Ok(results);}
    [HttpPost("requests/{requestId:guid}/compatibility-override"),RequirePermission(FleetPermissions.CompatibilityOverride)] public async Task<ActionResult<ApiResponse<object>>> Override(Guid requestId,CompatibilityOverrideRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason)||r.CapabilityIds.Length==0)return BadRequest(ApiResponse<object>.Fail("Reason and mismatches are required."));var request=await db.FleetRequests.Include(x=>x.StatusHistories).SingleOrDefaultAsync(x=>x.Id==requestId,ct);if(request is null)return NotFound(ApiResponse<object>.Fail("Request not found."));if(request.ConcurrencyToken!=r.RequestConcurrencyToken)return Conflict(ApiResponse<object>.Fail("Request changed."));var caps=await db.FleetCapabilities.Where(x=>r.CapabilityIds.Contains(x.Id)).ToListAsync(ct);if(caps.Count!=r.CapabilityIds.Distinct().Count()||caps.Any(x=>x.IsRequiredSafetyCapability))return BadRequest(ApiResponse<object>.Fail("Safety or unknown capability cannot be overridden."));var actor=Actor();var item=new FleetCompatibilityOverride{FleetRequestId=requestId,VehicleId=r.VehicleId,AssignmentId=r.AssignmentId,MismatchCapabilityIds=JsonSerializer.Serialize(r.CapabilityIds),Reason=r.Reason.Trim(),ApprovedByUserId=actor};db.Add(item);request.StatusHistories.Add(new(){FromStatus=request.Status,ToStatus=request.Status,Action="Fleet.CompatibilityOverridden",ActorUserId=actor,Reason=r.Reason.Trim(),CorrelationId=HttpContext.TraceIdentifier});db.AuditLogs.Add(new(){UserId=actor,EffectiveActorUserId=actor,Action="Fleet.CompatibilityOverridden",EntityName="FleetRequest",EntityId=requestId.ToString(),Detail=JsonSerializer.Serialize(new{r.VehicleId,r.CapabilityIds,Reason=r.Reason.Trim()}),CorrelationId=HttpContext.TraceIdentifier});request.ConcurrencyToken=Guid.NewGuid();await events.PublishAsync(new("Fleet.CompatibilityOverridden","FLEET","FleetRequest",requestId,actor,HttpContext.TraceIdentifier,new{requestId,r.VehicleId,r.CapabilityIds},[]),ct);await db.SaveChangesAsync(ct);return ApiResponse<object>.Ok(new{item.Id,request.ConcurrencyToken});}
    private Guid Actor()=>Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier)!);
}
