$ErrorActionPreference = "Stop"

$Script:DocsRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$Script:ProjectRoot = (Resolve-Path (Join-Path $Script:DocsRoot "..\..")).Path
$Script:Phase1Dir = Join-Path $Script:DocsRoot "phase1"
$Script:CombinedFile = Join-Path $Script:Phase1Dir "_combined.md"
$Script:TemplatesDir = Join-Path $Script:DocsRoot "templates"
$Script:MetadataFile = Join-Path $Script:TemplatesDir "metadata.yaml"
$Script:LatexTemplate = Join-Path $Script:TemplatesDir "hop-template.tex"
$Script:ReferenceDocx = Join-Path $Script:TemplatesDir "hop-reference.docx"
$Script:PdfDir = Join-Path $Script:DocsRoot "pdf"
$Script:DocxDir = Join-Path $Script:DocsRoot "docx"
$Script:HtmlDir = Join-Path $Script:DocsRoot "html"
$Script:QuickStartFile = Join-Path $Script:Phase1Dir "11-Quick-Start-One-Page.md"

function Write-Info {
    param([string]$Message)
    Write-Host "[INFO] $Message" -ForegroundColor Cyan
}

function Write-Ok {
    param([string]$Message)
    Write-Host "[OK] $Message" -ForegroundColor Green
}

function Write-Warn {
    param([string]$Message)
    Write-Host "[WARN] $Message" -ForegroundColor Yellow
}

function Write-Fail {
    param([string]$Message)
    Write-Host "[ERROR] $Message" -ForegroundColor Red
}

function Test-CommandAvailable {
    param([Parameter(Mandatory)][string]$Name)
    return [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

function Ensure-ManualDirectories {
    $directories = @(
        "assets\logo",
        "assets\icons",
        "assets\screenshots",
        "assets\diagrams",
        "assets\illustrations",
        "templates",
        "pdf",
        "docx",
        "html",
        "scripts"
    )

    foreach ($dir in $directories) {
        $path = Join-Path $Script:DocsRoot $dir
        if (-not (Test-Path $path)) {
            New-Item -ItemType Directory -Force -Path $path | Out-Null
            Write-Info "Created directory: $path"
        }
    }
}

function Get-Phase1MarkdownFiles {
    if (-not (Test-Path $Script:Phase1Dir)) {
        throw "Phase 1 directory not found: $Script:Phase1Dir"
    }

    $readme = Join-Path $Script:Phase1Dir "README.md"
    $files = New-Object System.Collections.Generic.List[System.IO.FileInfo]

    if (Test-Path $readme) {
        $files.Add((Get-Item $readme))
    }

    Get-ChildItem -Path $Script:Phase1Dir -Filter "*.md" -File |
        Where-Object { $_.Name -notin @("README.md", "_combined.md") } |
        Sort-Object Name |
        ForEach-Object { $files.Add($_) }

    return $files
}

function Build-CombinedMarkdown {
    Ensure-ManualDirectories
    $files = Get-Phase1MarkdownFiles

    if ($files.Count -eq 0) {
        throw "No Markdown files found in $Script:Phase1Dir"
    }

    $builder = New-Object System.Text.StringBuilder
    [void]$builder.AppendLine("<!--")
    [void]$builder.AppendLine("Generated by docs/manuals/scripts build process.")
    [void]$builder.AppendLine("Do not edit this file directly. Edit source Markdown files in docs/manuals/phase1/ instead.")
    [void]$builder.AppendLine("-->")
    [void]$builder.AppendLine()

    foreach ($file in $files) {
        Write-Info "Adding Markdown: $($file.Name)"
        [void]$builder.AppendLine()
        [void]$builder.AppendLine("<div class=""page-break""></div>")
        [void]$builder.AppendLine()
        [void]$builder.AppendLine((Get-Content -LiteralPath $file.FullName -Raw -Encoding UTF8))
        [void]$builder.AppendLine()
    }

    [System.IO.File]::WriteAllText($Script:CombinedFile, $builder.ToString(), [System.Text.UTF8Encoding]::new($false))
    Write-Ok "Combined Markdown written: $Script:CombinedFile"
}

function Get-PandocPath {
    $cmd = Get-Command pandoc -ErrorAction SilentlyContinue
    if (-not $cmd) {
        throw "Pandoc is required but was not found. Run .\docs\manuals\scripts\install-tools-windows.ps1 or install Pandoc manually."
    }
    return $cmd.Source
}

function Test-LatexAvailable {
    return (Test-CommandAvailable "xelatex") -or (Test-CommandAvailable "lualatex")
}

function Get-LatexEngine {
    if (Test-CommandAvailable "xelatex") { return "xelatex" }
    if (Test-CommandAvailable "lualatex") { return "lualatex" }
    throw "No LaTeX engine found. Install MiKTeX or TinyTeX with xelatex."
}

function Invoke-ExternalCommand {
    param(
        [Parameter(Mandatory)][string]$FilePath,
        [Parameter(Mandatory)][string[]]$Arguments,
        [Parameter(Mandatory)][string]$ErrorMessage
    )

    Write-Info "Running: $FilePath $($Arguments -join ' ')"
    & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "$ErrorMessage Exit code: $LASTEXITCODE"
    }
}
