FROM node:20-alpine AS build
WORKDIR /app
ARG VITE_API_BASE_URL=
ARG VITE_APP_NAME="Hospital Operations Portal"
ARG VITE_HOSPITAL_NAME="โรงพยาบาลนาหมื่น"
ARG VITE_APP_VERSION=1.0.0
ARG VITE_APP_DEVELOPER="งานเทคโนโลยีสารสนเทศ"
ARG VITE_LIFF_ID=
ARG VITE_LIFF_BASE_URL=https://miniapp.line.me
ARG VITE_HIDE_INELIGIBLE_LEAVE_TYPES=true
ARG VITE_MAX_UPLOAD_SIZE_MB=5
ARG VITE_AUTH_TOKEN_STORAGE_MODE=cookie
ARG VITE_AUTH_CSRF_COOKIE_NAME=hop_csrf_token
ARG VITE_AUTH_CSRF_HEADER_NAME=X-CSRF-TOKEN
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_APP_NAME=$VITE_APP_NAME
ENV VITE_HOSPITAL_NAME=$VITE_HOSPITAL_NAME
ENV VITE_APP_VERSION=$VITE_APP_VERSION
ENV VITE_APP_DEVELOPER=$VITE_APP_DEVELOPER
ENV VITE_LIFF_ID=$VITE_LIFF_ID
ENV VITE_LIFF_BASE_URL=$VITE_LIFF_BASE_URL
ENV VITE_HIDE_INELIGIBLE_LEAVE_TYPES=$VITE_HIDE_INELIGIBLE_LEAVE_TYPES
ENV VITE_MAX_UPLOAD_SIZE_MB=$VITE_MAX_UPLOAD_SIZE_MB
ENV VITE_AUTH_TOKEN_STORAGE_MODE=$VITE_AUTH_TOKEN_STORAGE_MODE
ENV VITE_AUTH_CSRF_COOKIE_NAME=$VITE_AUTH_CSRF_COOKIE_NAME
ENV VITE_AUTH_CSRF_HEADER_NAME=$VITE_AUTH_CSRF_HEADER_NAME

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ ./
RUN npm run build

FROM nginxinc/nginx-unprivileged:1.27-alpine AS runtime
COPY --from=build --chown=nginx:nginx /app/dist /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
