using Hop.Api.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Hop.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260914150000_AddMeetingRoomBooking")]
public sealed class AddMeetingRoomBooking : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder) => migrationBuilder.Sql(SchemaSql);
    protected override void Down(MigrationBuilder migrationBuilder) => migrationBuilder.Sql("""
        DROP TABLE IF EXISTS meeting_room_attachments;
        DROP TABLE IF EXISTS meeting_room_booking_histories;
        DROP TABLE IF EXISTS meeting_room_bookings;
        DROP TABLE IF EXISTS meeting_rooms;
        DELETE FROM role_permissions rp USING permissions p WHERE rp.permission_id=p.id AND p.code LIKE 'MeetingRoom.%';
        DELETE FROM permissions WHERE code LIKE 'MeetingRoom.%';
        DELETE FROM roles WHERE name='ผู้ดูแลห้องประชุม' AND NOT EXISTS (SELECT 1 FROM user_roles ur WHERE ur.role_id=roles.id);
        """);

    internal const string SchemaSql = """
        CREATE TABLE IF NOT EXISTS meeting_rooms (
          id uuid PRIMARY KEY, code varchar(50) NOT NULL UNIQUE, name varchar(200) NOT NULL,
          location varchar(500) NOT NULL, capacity integer NOT NULL CHECK(capacity > 0), is_active boolean NOT NULL DEFAULT true,
          concurrency_token uuid NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NULL);
        CREATE TABLE IF NOT EXISTS meeting_room_bookings (
          id uuid PRIMARY KEY, number bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE, room_id uuid NOT NULL REFERENCES meeting_rooms(id) ON DELETE RESTRICT,
          booker_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, department_id uuid NULL REFERENCES departments(id) ON DELETE RESTRICT,
          subject varchar(300) NOT NULL, purpose varchar(4000) NOT NULL, start_at timestamptz NOT NULL, end_at timestamptz NOT NULL,
          attendee_count integer NOT NULL CHECK(attendee_count > 0), meeting_link varchar(1000) NULL, additional_request varchar(2000) NULL,
          status varchar(30) NOT NULL, cancellation_reason varchar(2000) NULL, cancelled_by_id uuid NULL REFERENCES users(id) ON DELETE RESTRICT,
          cancelled_at timestamptz NULL, concurrency_token uuid NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL,
          CONSTRAINT ck_meeting_room_booking_time CHECK(end_at > start_at));
        CREATE INDEX IF NOT EXISTS ix_meeting_room_bookings_room_time ON meeting_room_bookings(room_id,start_at,end_at);
        CREATE INDEX IF NOT EXISTS ix_meeting_room_bookings_booker_time ON meeting_room_bookings(booker_id,start_at);
        CREATE TABLE IF NOT EXISTS meeting_room_booking_histories (
          id uuid PRIMARY KEY, booking_id uuid NOT NULL REFERENCES meeting_room_bookings(id) ON DELETE RESTRICT,
          actor_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, action varchar(50) NOT NULL, from_status varchar(30) NOT NULL,
          to_status varchar(30) NOT NULL, detail varchar(4000) NULL, created_at timestamptz NOT NULL);
        CREATE INDEX IF NOT EXISTS ix_meeting_room_booking_histories_booking_created ON meeting_room_booking_histories(booking_id,created_at);
        CREATE TABLE IF NOT EXISTS meeting_room_attachments (
          id uuid PRIMARY KEY, booking_id uuid NOT NULL REFERENCES meeting_room_bookings(id) ON DELETE RESTRICT,
          uploaded_by_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT, original_file_name varchar(500) NOT NULL,
          stored_path varchar(1000) NOT NULL, content_type varchar(200) NOT NULL, file_size bigint NOT NULL, created_at timestamptz NOT NULL);
        CREATE INDEX IF NOT EXISTS ix_meeting_room_attachments_booking_created ON meeting_room_attachments(booking_id,created_at);

        INSERT INTO roles(id,name,description,is_system_role,is_active,created_at)
        SELECT gen_random_uuid(),'ผู้ดูแลห้องประชุม','จัดการทะเบียนห้องและรายการจอง',true,true,now()
        WHERE NOT EXISTS(SELECT 1 FROM roles WHERE name='ผู้ดูแลห้องประชุม');
        INSERT INTO permissions(id,code,name,group_name,action,is_active,created_at)
        SELECT gen_random_uuid(),v.code,v.name,'MeetingRoom',v.action,true,now() FROM (VALUES
          ('MeetingRoom.Calendar.View','ดูปฏิทินห้องประชุม','View'),('MeetingRoom.Booking.ViewOwn','ดูรายการจองของตนเอง','ViewOwn'),
          ('MeetingRoom.Booking.Create','จองห้องประชุม','Create'),('MeetingRoom.Booking.Manage','จัดการรายการจองทั้งหมด','Manage'),
          ('MeetingRoom.Room.Manage','จัดการทะเบียนห้องประชุม','ManageRooms')) v(code,name,action)
        WHERE NOT EXISTS(SELECT 1 FROM permissions p WHERE p.code=v.code);
        INSERT INTO role_permissions(role_id,permission_id)
        SELECT r.id,p.id FROM roles r CROSS JOIN permissions p
        WHERE r.is_active AND p.code IN ('MeetingRoom.Calendar.View','MeetingRoom.Booking.ViewOwn','MeetingRoom.Booking.Create')
        ON CONFLICT DO NOTHING;
        INSERT INTO role_permissions(role_id,permission_id)
        SELECT r.id,p.id FROM roles r CROSS JOIN permissions p
        WHERE r.name IN ('ผู้ดูแลห้องประชุม','Admin','SuperAdmin') AND p.code LIKE 'MeetingRoom.%'
        ON CONFLICT DO NOTHING;
        """;
}
