import { useState } from "react";
import { Alert, Box, Button, Card, CardActionArea, CardContent, Chip, CircularProgress, MenuItem, Stack, TextField, Typography } from "@mui/material";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { getFleetHealth, getFleetHealthIssues } from "../api/fleetApi";
import { PageHeader } from "../components/PageHeader";

export function FleetHealthPage() {
  const [severity, setSeverity] = useState(""); const health = useQuery({ queryKey: ["fleet-health"], queryFn: getFleetHealth }); const issues = useQuery({ queryKey: ["fleet-health-issues", severity], queryFn: () => getFleetHealthIssues(severity) }); const refresh = () => { void health.refetch(); void issues.refetch(); };
  return <><PageHeader title="Fleet Health Center" subtitle="สถานะ workflow, availability, Outbox และ notification delivery" /><Stack direction={{ xs: "column", sm: "row" }} spacing={1} sx={{ mb: 2 }}><TextField select size="small" label="Severity" value={severity} onChange={e => setSeverity(e.target.value)} sx={{ minWidth: 180 }}><MenuItem value="">ทั้งหมด</MenuItem><MenuItem value="Warning">Warning</MenuItem><MenuItem value="Critical">Critical</MenuItem></TextField><Button variant="outlined" onClick={refresh}>Refresh</Button></Stack>{health.isLoading ? <Stack alignItems="center"><CircularProgress /></Stack> : health.isError ? <Alert severity="error" action={<Button onClick={refresh}>ลองใหม่</Button>}>โหลด Fleet Health ไม่สำเร็จ</Alert> : <Stack spacing={2}><Alert severity={health.data?.status === "Critical" ? "error" : health.data?.status === "Warning" ? "warning" : "success"}>สถานะ {health.data?.status} · Warning {health.data?.warningCount} · Critical {health.data?.criticalCount}</Alert><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", sm: "repeat(2, 1fr)", lg: "repeat(4, 1fr)" }, gap: 2 }}>{health.data?.metrics.map(x => <Card key={x.key}>{x.actionUrl ? <CardActionArea component={Link} to={x.actionUrl}><Metric label={x.label} value={x.value} /></CardActionArea> : <Metric label={x.label} value={x.value} />}</Card>)}</Box><Card><CardContent><Typography variant="h6" sx={{ mb: 1 }}>Issues</Typography>{issues.isLoading ? <Typography>กำลังโหลด...</Typography> : issues.isError ? <Alert severity="error">โหลดปัญหาไม่สำเร็จ</Alert> : issues.data?.length === 0 ? <Typography color="text.secondary">ไม่พบปัญหาตามตัวกรอง</Typography> : <Stack spacing={1}>{issues.data?.map(x => <Alert key={`${x.code}-${x.entityId}`} severity={x.severity === "Critical" ? "error" : "warning"} action={x.actionUrl ? <Button component={Link} to={x.actionUrl}>เปิดรายการ</Button> : undefined}><Chip size="small" label={x.code} sx={{ mr: 1 }} />{x.message}</Alert>)}</Stack>}</CardContent></Card></Stack>}</>;
}
function Metric({ label, value }: { label: string; value: number }) { return <CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h4">{value.toLocaleString("th-TH")}</Typography></CardContent>; }
