import { useMemo, useState } from "react";
import type { ReactNode } from "react";
import { isAxiosError } from "axios";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import AddOutlinedIcon from "@mui/icons-material/AddOutlined";
import DirectionsCarOutlinedIcon from "@mui/icons-material/DirectionsCarOutlined";
import EditOutlinedIcon from "@mui/icons-material/EditOutlined";
import PersonOutlineOutlinedIcon from "@mui/icons-material/PersonOutlineOutlined";
import PeopleOutlineOutlinedIcon from "@mui/icons-material/PeopleOutlineOutlined";
import SearchOutlinedIcon from "@mui/icons-material/SearchOutlined";
import SpeedOutlinedIcon from "@mui/icons-material/SpeedOutlined";
import GridViewOutlinedIcon from "@mui/icons-material/GridViewOutlined";
import ViewListOutlinedIcon from "@mui/icons-material/ViewListOutlined";
import { Alert, Box, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, FormControlLabel, Grid, IconButton, InputAdornment, MenuItem, Stack, Switch, Tab, Tabs, TextField, Tooltip, Typography } from "@mui/material";
import { PageHeader } from "../components/PageHeader";
import { AppDatePicker } from "../components/common/AppDatePicker";
import { ActionDialog } from "../components/common/ActionDialog";
import { EmptyState } from "../components/common/EmptyState";
import { LoadingState } from "../components/common/LoadingState";
import { usePermission } from "../context/PermissionContext";
import { formatThaiDate, formatThaiYear, parseThaiCalendarYear } from "../utils/dateFormat";
import { createFleetDriverProfile, createFleetVehicle, getFleetDriverProfiles, getFleetMasterDepartments, getFleetMasterPersonnel, getFleetVehicleRecords, getFleetVehicleTypes, setFleetDriverActive, setFleetVehicleActive, updateFleetDriverProfile, updateFleetVehicle, type FleetDriverProfile, type FleetVehicleRecord, type SaveFleetDriverProfile, type SaveFleetVehicle } from "../api/fleetApi";
import vehicleSprite from "../assets/fleet/vehicle-sprite.png";
import wave125Sprite from "../assets/fleet/vehicle-sprite-wave125.png";

const vehicleStatuses = [["AVAILABLE", "พร้อมใช้งาน"], ["RESERVED", "ถูกจอง"], ["IN_USE", "กำลังใช้งาน"], ["MAINTENANCE", "ซ่อมบำรุง"], ["TEMPORARILY_UNAVAILABLE", "ไม่พร้อมชั่วคราว"], ["DECOMMISSIONED", "ปลดระวาง"]];
const driverStatuses = [["AVAILABLE", "พร้อมขับ"], ["UNAVAILABLE", "ไม่พร้อม"], ["SUSPENDED", "ระงับ"]];
const emptyVehicle: SaveFleetVehicle = { vehicleCode: "", registrationNumber: "", registrationProvince: "", vehicleTypeId: "", brand: "", model: "", manufactureYear: null, seatCapacityTotal: 1, passengerCapacity: 1, fuelType: "", currentMileage: 0, owningDepartmentId: null, responsibleUserId: null, status: "AVAILABLE", isActive: true, note: "" };
const emptyDriver: SaveFleetDriverProfile = { userId: "", licenseNumber: "", licenseType: "", licenseIssueDate: null, licenseExpiryDate: null, canDriveSedan: false, canDrivePickup: false, canDriveVan: false, canDriveAmbulance: false, canDriveOther: false, driverStatus: "AVAILABLE", isActive: true, note: "" };
const errorText = (error: unknown) => isAxiosError<{message?:string}>(error) ? error.response?.data?.message ?? "บันทึกไม่สำเร็จ กรุณาลองอีกครั้ง" : "บันทึกไม่สำเร็จ กรุณาลองอีกครั้ง";

export function FleetSettingsPage() {
  const { hasPermission } = usePermission();
  const canVehicles = hasPermission("FleetVehicle.Manage");
  const canDrivers = hasPermission("FleetDriver.Manage");
  const [tab, setTab] = useState(canVehicles ? 0 : 1);
  const vehicleCount = useQuery({ queryKey:["fleet","settings","vehicles"], queryFn:getFleetVehicleRecords, enabled:canVehicles });
  const driverCount = useQuery({ queryKey:["fleet","settings","drivers"], queryFn:getFleetDriverProfiles, enabled:canDrivers });
  return <Stack spacing={2}>
    <PageHeader title="จัดการรถและคนขับ" subtitle="ทะเบียนรถ ข้อมูลคนขับ และใบขับขี่สำหรับงานยานพาหนะ" />
    <Tabs value={tab} onChange={(_, value:number) => setTab(value)} aria-label="ตั้งค่าระบบรถ" variant="scrollable" scrollButtons="auto" sx={{ borderBottom: 1, borderColor: "divider", "& .MuiTab-root":{minHeight:52,fontWeight:800} }}>
      {canVehicles && <Tab value={0} icon={<DirectionsCarOutlinedIcon />} iconPosition="start" label={`รถ (${vehicleCount.data?.length ?? 0})`} />}{canDrivers && <Tab value={1} icon={<PersonOutlineOutlinedIcon />} iconPosition="start" label={`คนขับ (${driverCount.data?.length ?? 0})`} />}
    </Tabs>
    {tab === 0 && canVehicles && <VehicleManager />}
    {tab === 1 && canDrivers && <DriverManager />}
    {!canVehicles && !canDrivers && <Alert severity="info">บัญชีนี้ไม่มีสิทธิ์จัดการรถหรือคนขับ</Alert>}
  </Stack>;
}

function VehicleManager() {
  const queryClient = useQueryClient();
  const vehicles = useQuery({ queryKey:["fleet","settings","vehicles"], queryFn:getFleetVehicleRecords });
  const types = useQuery({ queryKey:["fleet","vehicle-types"], queryFn:getFleetVehicleTypes });
  const departments = useQuery({ queryKey:["fleet","settings","departments"], queryFn:getFleetMasterDepartments });
  const personnel = useQuery({ queryKey:["fleet","settings","personnel"], queryFn:getFleetMasterPersonnel });
  const [search,setSearch] = useState(""); const [statusFilter,setStatusFilter] = useState("all"); const [typeFilter,setTypeFilter] = useState("all"); const [sortBy,setSortBy] = useState("registration"); const [viewMode,setViewMode] = useState<"grid"|"list">("grid"); const [editing,setEditing] = useState<FleetVehicleRecord|null>(null); const [open,setOpen] = useState(false);
  const [confirmItem,setConfirmItem] = useState<FleetVehicleRecord|null>(null); const [success,setSuccess] = useState("");
  const [form,setForm] = useState<SaveFleetVehicle>(emptyVehicle); const [error,setError] = useState("");
  const [manufactureYearInput,setManufactureYearInput] = useState("");
  const manufactureYearValid = !manufactureYearInput || parseThaiCalendarYear(manufactureYearInput) !== null;
  const refresh = () => { void queryClient.invalidateQueries({ queryKey:["fleet","settings","vehicles"] }); void queryClient.invalidateQueries({ queryKey:["fleet","vehicles"] }); };
  const save = useMutation({ mutationFn: () => editing ? updateFleetVehicle(editing.id,form) : createFleetVehicle(form), onSuccess:() => { setOpen(false); setSuccess(editing ? "บันทึกข้อมูลรถเรียบร้อยแล้ว" : "เพิ่มรถเรียบร้อยแล้ว"); refresh(); }, onError:e => setError(errorText(e)) });
  const active = useMutation({ mutationFn:({id,isActive}:{id:string;isActive:boolean}) => setFleetVehicleActive(id,isActive), onSuccess:() => { setSuccess(confirmItem?.isActive ? "ปิดใช้งานรถเรียบร้อยแล้ว" : "เปิดใช้งานรถเรียบร้อยแล้ว"); setConfirmItem(null); refresh(); }, onError:e => { setConfirmItem(null); setError(errorText(e)); } });
  const rows = useMemo(() => (vehicles.data ?? []).filter(x => (statusFilter === "all" || x.isActive === (statusFilter === "active")) && (typeFilter === "all" || x.vehicleTypeId === typeFilter) && `${x.vehicleCode} ${x.registrationNumber} ${x.vehicleTypeName} ${x.brand ?? ""} ${x.model ?? ""}`.toLowerCase().includes(search.trim().toLowerCase())).sort((a,b)=>sortBy === "mileage" ? a.currentMileage-b.currentMileage : sortBy === "code" ? a.vehicleCode.localeCompare(b.vehicleCode,"th") : a.registrationNumber.localeCompare(b.registrationNumber,"th")),[vehicles.data,search,statusFilter,typeFilter,sortBy]);
  const field = <K extends keyof SaveFleetVehicle>(key:K,value:SaveFleetVehicle[K]) => setForm(current => ({...current,[key]:value}));
  const start = (item?:FleetVehicleRecord) => { setEditing(item ?? null); setForm(item ? { vehicleCode:item.vehicleCode, registrationNumber:item.registrationNumber, registrationProvince:item.registrationProvince, vehicleTypeId:item.vehicleTypeId, brand:item.brand, model:item.model, manufactureYear:item.manufactureYear, seatCapacityTotal:item.seatCapacityTotal, passengerCapacity:item.passengerCapacity, fuelType:item.fuelType, currentMileage:item.currentMileage, owningDepartmentId:item.owningDepartmentId, responsibleUserId:item.responsibleUserId, status:item.status, isActive:item.isActive, note:item.note } : {...emptyVehicle}); setManufactureYearInput(item?.manufactureYear ? formatThaiYear(item.manufactureYear) : ""); setError(""); setOpen(true); };
  return <Stack spacing={2}>
    <ManagementToolbar title="รายการรถ" total={vehicles.data?.length ?? 0} active={(vehicles.data ?? []).filter(x=>x.isActive).length} actionLabel="เพิ่มรถ" onAdd={()=>start()} search={search} onSearch={setSearch} searchLabel="ค้นหาทะเบียนรถ รุ่น ประเภท หรือคำสำคัญ..." statusFilter={statusFilter} onStatusFilter={setStatusFilter} viewMode={viewMode} onViewMode={setViewMode} extraFilters={<><TextField size="small" select label="ประเภทรถ" value={typeFilter} onChange={e=>setTypeFilter(e.target.value)} sx={{minWidth:{sm:155}}}><MenuItem value="all">ทุกประเภท</MenuItem>{(types.data ?? []).map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField><TextField size="small" select label="เรียงตาม" value={sortBy} onChange={e=>setSortBy(e.target.value)} sx={{minWidth:{sm:175}}}><MenuItem value="registration">ทะเบียน (ก-ฮ)</MenuItem><MenuItem value="code">รหัสรถ</MenuItem><MenuItem value="mileage">เลขไมล์น้อยสุด</MenuItem></TextField></>} />
    {vehicles.isError && <Alert severity="error" action={<Button onClick={()=>void vehicles.refetch()}>ลองใหม่</Button>}>โหลดข้อมูลรถไม่สำเร็จ</Alert>}
    {error && !open && <Alert severity="error">{error}</Alert>}
    {success && <Alert severity="success" onClose={()=>setSuccess("")}>{success}</Alert>}
    {vehicles.isLoading && <LoadingState message="กำลังโหลดข้อมูลรถ..." />}
    {!vehicles.isLoading && !vehicles.isError && rows.length === 0 && <EmptyState title={vehicles.data?.length ? "ไม่พบรถตามเงื่อนไข" : "ยังไม่มีข้อมูลรถ"} description={vehicles.data?.length ? "ลองเปลี่ยนคำค้นหาหรือตัวกรองสถานะ" : "เพิ่มรถคันแรกเพื่อเริ่มจัดการทะเบียนรถ"} />}
    <Grid container spacing={2}>{rows.map(item=><Grid item xs={12} sm={viewMode === "grid" ? 6 : 12} lg={viewMode === "grid" ? 4 : 12} xl={viewMode === "grid" ? 3 : 12} key={item.id}><VehicleCard item={item} compact={viewMode === "list"} onEdit={()=>start(item)} onToggle={()=>{setError("");setConfirmItem(item);}} toggleDisabled={active.isPending} /></Grid>)}</Grid>
    <ActionDialog open={Boolean(confirmItem)} title={`ยืนยัน${confirmItem?.isActive ? "ปิด" : "เปิด"}ใช้งานรถ`} confirmLabel={confirmItem?.isActive ? "ปิดใช้งาน" : "เปิดใช้งาน"} confirmColor={confirmItem?.isActive ? "error" : "success"} isLoading={active.isPending} onClose={()=>setConfirmItem(null)} onConfirm={()=>confirmItem && active.mutate({id:confirmItem.id,isActive:!confirmItem.isActive})}><Typography>รถ “{confirmItem?.registrationNumber}” {confirmItem?.isActive ? "จะไม่ปรากฏเป็นตัวเลือกสำหรับการจัดรถใหม่ และอาจปิดใช้งานไม่ได้หากยังมีงานค้าง" : "จะกลับมาเป็นตัวเลือกสำหรับการจัดรถใหม่"}</Typography></ActionDialog>
    <Dialog open={open} onClose={()=>setOpen(false)} maxWidth="md" fullWidth fullScreen={false}><DialogTitle>{editing ? "รายละเอียดและแก้ไขรถ" : "เพิ่มรถ"}</DialogTitle><DialogContent dividers><Stack spacing={2} sx={{pt:1}}><Typography variant="body2" color="text.secondary">กรอกข้อมูลทะเบียน ความจุ และผู้รับผิดชอบ ข้อมูลนี้ใช้ตอนจัดรถและตรวจสอบประวัติ</Typography>{error && <Alert severity="error">{error}</Alert>}<Grid container spacing={2}>
      <Grid item xs={12}><Typography fontWeight={800}>ข้อมูลรถ</Typography><Divider sx={{mt:1}} /></Grid>
      <Grid item xs={12} sm={6}><TextField required fullWidth label="รหัสรถ" value={form.vehicleCode} onChange={e=>field("vehicleCode",e.target.value)} /></Grid><Grid item xs={12} sm={6}><TextField required fullWidth label="ทะเบียนรถ" value={form.registrationNumber} onChange={e=>field("registrationNumber",e.target.value)} /></Grid>
      <Grid item xs={12} sm={6}><TextField fullWidth label="จังหวัดทะเบียน" value={form.registrationProvince ?? ""} onChange={e=>field("registrationProvince",e.target.value)} /></Grid><Grid item xs={12} sm={6}><TextField required fullWidth select label="ประเภทรถ" value={form.vehicleTypeId} onChange={e=>field("vehicleTypeId",e.target.value)}>{(types.data ?? []).filter(x=>x.isActive || x.id===form.vehicleTypeId).map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField></Grid>
      <Grid item xs={12} sm={6}><TextField fullWidth label="ยี่ห้อ" value={form.brand ?? ""} onChange={e=>field("brand",e.target.value)} /></Grid><Grid item xs={12} sm={6}><TextField fullWidth label="รุ่น" value={form.model ?? ""} onChange={e=>field("model",e.target.value)} /></Grid>
      <Grid item xs={12}><Typography fontWeight={800}>ความจุและการใช้งาน</Typography><Divider sx={{mt:1}} /></Grid>
      <Grid item xs={12} sm={4}><TextField fullWidth type="number" label="ปีผลิต พ.ศ." value={manufactureYearInput} onChange={e=>{setManufactureYearInput(e.target.value);field("manufactureYear",e.target.value ? parseThaiCalendarYear(e.target.value) : null);}} error={!manufactureYearValid} helperText={manufactureYearValid ? "กรอก พ.ศ. หรือ ค.ศ.; บันทึกเป็น ค.ศ." : "กรอกปี พ.ศ. 2443–2643 หรือ ค.ศ. 1900–2100"} /></Grid><Grid item xs={12} sm={4}><TextField required fullWidth type="number" label="จำนวนที่นั่งรวม" value={form.seatCapacityTotal} onChange={e=>field("seatCapacityTotal",Number(e.target.value))} /></Grid><Grid item xs={12} sm={4}><TextField required fullWidth type="number" label="ความจุผู้โดยสาร" value={form.passengerCapacity} onChange={e=>field("passengerCapacity",Number(e.target.value))} error={form.passengerCapacity<1 || form.seatCapacityTotal<form.passengerCapacity} helperText={form.seatCapacityTotal<form.passengerCapacity ? "ผู้โดยสารต้องไม่เกินจำนวนที่นั่งรวม" : undefined} /></Grid>
      <Grid item xs={12} sm={6}><TextField fullWidth label="เชื้อเพลิง" value={form.fuelType ?? ""} onChange={e=>field("fuelType",e.target.value)} /></Grid><Grid item xs={12} sm={6}><TextField fullWidth type="number" label="เลขไมล์ปัจจุบัน" value={form.currentMileage} onChange={e=>field("currentMileage",Number(e.target.value))} /></Grid>
      <Grid item xs={12}><Typography fontWeight={800}>หน่วยงานและสถานะ</Typography><Divider sx={{mt:1}} /></Grid>
      <Grid item xs={12} sm={6}><TextField fullWidth select label="หน่วยงานเจ้าของรถ" value={form.owningDepartmentId ?? ""} onChange={e=>field("owningDepartmentId",e.target.value || null)}><MenuItem value="">ไม่ระบุ</MenuItem>{(departments.data ?? []).map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6}><TextField fullWidth select label="ผู้รับผิดชอบ" value={form.responsibleUserId ?? ""} onChange={e=>field("responsibleUserId",e.target.value || null)}><MenuItem value="">ไม่ระบุ</MenuItem>{(personnel.data ?? []).map(x=><MenuItem key={x.id} value={x.id}>{x.fullName}</MenuItem>)}</TextField></Grid>
      <Grid item xs={12} sm={6}><TextField fullWidth select label="สถานะรถ" value={form.status} onChange={e=>field("status",e.target.value)}>{vehicleStatuses.map(([value,label])=><MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6}><FormControlLabel control={<Switch checked={form.isActive} onChange={(_,value)=>field("isActive",value)} />} label="เปิดใช้งาน" /></Grid>
      <Grid item xs={12}><TextField fullWidth multiline minRows={2} label="หมายเหตุ" value={form.note ?? ""} onChange={e=>field("note",e.target.value)} /></Grid>
    </Grid></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>ยกเลิก</Button><Button variant="contained" disabled={save.isPending || !form.vehicleCode.trim() || !form.registrationNumber.trim() || !form.vehicleTypeId || !manufactureYearValid || form.passengerCapacity<1 || form.seatCapacityTotal<form.passengerCapacity || form.currentMileage<0} onClick={()=>save.mutate()}>บันทึก</Button></DialogActions></Dialog>
  </Stack>;
}

function DriverManager() {
  const queryClient = useQueryClient();
  const drivers = useQuery({ queryKey:["fleet","settings","drivers"], queryFn:getFleetDriverProfiles });
  const personnel = useQuery({ queryKey:["fleet","settings","personnel"], queryFn:getFleetMasterPersonnel });
  const [search,setSearch] = useState(""); const [statusFilter,setStatusFilter] = useState("all"); const [viewMode,setViewMode] = useState<"grid"|"list">("grid"); const [editing,setEditing] = useState<FleetDriverProfile|null>(null); const [open,setOpen] = useState(false);
  const [confirmItem,setConfirmItem] = useState<FleetDriverProfile|null>(null); const [success,setSuccess] = useState("");
  const [form,setForm] = useState<SaveFleetDriverProfile>(emptyDriver); const [error,setError] = useState("");
  const refresh = () => { void queryClient.invalidateQueries({queryKey:["fleet","settings","drivers"]}); void queryClient.invalidateQueries({queryKey:["fleet","availability"]}); };
  const save = useMutation({ mutationFn:() => editing ? updateFleetDriverProfile(editing.id,form) : createFleetDriverProfile(form), onSuccess:()=>{setOpen(false);setSuccess(editing ? "บันทึกข้อมูลคนขับเรียบร้อยแล้ว" : "เพิ่มคนขับเรียบร้อยแล้ว");refresh();}, onError:e=>setError(errorText(e)) });
  const active = useMutation({ mutationFn:({id,isActive}:{id:string;isActive:boolean})=>setFleetDriverActive(id,isActive), onSuccess:()=>{setSuccess(confirmItem?.isActive ? "ปิดใช้งานคนขับเรียบร้อยแล้ว" : "เปิดใช้งานคนขับเรียบร้อยแล้ว");setConfirmItem(null);refresh();}, onError:e=>{setConfirmItem(null);setError(errorText(e));} });
  const rows = useMemo(()=>(drivers.data ?? []).filter(x=>(statusFilter === "all" || x.isActive === (statusFilter === "active")) && `${x.fullName} ${x.employeeCode} ${x.licenseType} ${x.licenseNumber}`.toLowerCase().includes(search.trim().toLowerCase())),[drivers.data,search,statusFilter]);
  const field = <K extends keyof SaveFleetDriverProfile>(key:K,value:SaveFleetDriverProfile[K]) => setForm(current=>({...current,[key]:value}));
  const start = (item?:FleetDriverProfile) => { setEditing(item ?? null); setForm(item ? { userId:item.userId, licenseNumber:item.licenseNumber, licenseType:item.licenseType, licenseIssueDate:item.licenseIssueDate, licenseExpiryDate:item.licenseExpiryDate, canDriveSedan:item.canDriveSedan, canDrivePickup:item.canDrivePickup, canDriveVan:item.canDriveVan, canDriveAmbulance:item.canDriveAmbulance, canDriveOther:item.canDriveOther, driverStatus:item.driverStatus, isActive:item.isActive, note:item.note } : {...emptyDriver}); setError(""); setOpen(true); };
  const candidates = (personnel.data ?? []).filter(x=>x.id===form.userId || !(drivers.data ?? []).some(driver=>driver.userId===x.id));
  return <Stack spacing={2}>
    <ManagementToolbar title="รายการคนขับ" total={drivers.data?.length ?? 0} active={(drivers.data ?? []).filter(x=>x.isActive).length} actionLabel="เพิ่มคนขับ" onAdd={()=>start()} search={search} onSearch={setSearch} searchLabel="ค้นหาชื่อ รหัสพนักงาน หรือใบขับขี่" statusFilter={statusFilter} onStatusFilter={setStatusFilter} viewMode={viewMode} onViewMode={setViewMode} />
    {drivers.isError && <Alert severity="error" action={<Button onClick={()=>void drivers.refetch()}>ลองใหม่</Button>}>โหลดข้อมูลคนขับไม่สำเร็จ</Alert>}
    {error && !open && <Alert severity="error">{error}</Alert>}
    {success && <Alert severity="success" onClose={()=>setSuccess("")}>{success}</Alert>}
    {drivers.isLoading && <LoadingState message="กำลังโหลดข้อมูลคนขับ..." />}
    {!drivers.isLoading && !drivers.isError && rows.length === 0 && <EmptyState title={drivers.data?.length ? "ไม่พบคนขับตามเงื่อนไข" : "ยังไม่มีข้อมูลคนขับ"} description={drivers.data?.length ? "ลองเปลี่ยนคำค้นหาหรือตัวกรองสถานะ" : "เพิ่มพนักงานที่ได้รับมอบหมายให้ขับรถ"} />}
    <Grid container spacing={2}>{rows.map(item=><Grid item xs={12} sm={viewMode === "grid" ? 6 : 12} lg={viewMode === "grid" ? 4 : 12} xl={viewMode === "grid" ? 3 : 12} key={item.id}><Card variant="outlined" sx={{height:"100%",borderColor:"#e9dfd1",borderRadius:3,boxShadow:"0 8px 22px rgba(34,70,55,.05)"}}><CardContent sx={{height:"100%",display:"flex",flexDirection:"column",gap:1.2}}><Stack direction="row" spacing={1.5} alignItems="center"><Box sx={{width:52,height:52,borderRadius:"50%",bgcolor:"#e5f1eb",color:"#245c50",display:"grid",placeItems:"center",flexShrink:0}}><PersonOutlineOutlinedIcon fontSize="large" /></Box><Box sx={{minWidth:0}}><Typography variant="h6" fontWeight={800} sx={{overflowWrap:"anywhere"}}>{item.fullName}</Typography><Typography variant="body2" color="text.secondary">รหัส {item.employeeCode || "-"}</Typography></Box></Stack><Stack direction="row" spacing={.75} flexWrap="wrap" useFlexGap><Chip size="small" label={item.isActive ? "เปิดใช้งาน" : "ปิดใช้งาน"} color={item.isActive ? "success" : "default"} /><Chip size="small" variant="outlined" label={driverStatuses.find(([code])=>code===item.driverStatus)?.[1] ?? item.driverStatus} /></Stack><Typography variant="body2" sx={{overflowWrap:"anywhere"}}>ใบขับขี่ {item.licenseType} · {item.licenseNumber}</Typography><Typography variant="body2" color="text.secondary">หมดอายุ {formatThaiDate(item.licenseExpiryDate)}</Typography><Stack direction="row" spacing={1} sx={{mt:"auto",pt:1}}><Button fullWidth variant="outlined" startIcon={<EditOutlinedIcon />} onClick={()=>start(item)} sx={{minHeight:42}}>ดู/แก้ไข</Button><Button fullWidth variant="outlined" color={item.isActive ? "error" : "success"} disabled={active.isPending} onClick={()=>{setError("");setConfirmItem(item);}} sx={{minHeight:42}}>{item.isActive ? "ปิดใช้งาน" : "เปิดใช้งาน"}</Button></Stack></CardContent></Card></Grid>)}</Grid>
    <ActionDialog open={Boolean(confirmItem)} title={`ยืนยัน${confirmItem?.isActive ? "ปิด" : "เปิด"}ใช้งานคนขับ`} confirmLabel={confirmItem?.isActive ? "ปิดใช้งาน" : "เปิดใช้งาน"} confirmColor={confirmItem?.isActive ? "error" : "success"} isLoading={active.isPending} onClose={()=>setConfirmItem(null)} onConfirm={()=>confirmItem && active.mutate({id:confirmItem.id,isActive:!confirmItem.isActive})}><Typography>คนขับ “{confirmItem?.fullName}” {confirmItem?.isActive ? "จะไม่ปรากฏเป็นตัวเลือกสำหรับการจัดงานใหม่ และอาจปิดใช้งานไม่ได้หากยังมีงานค้าง" : "จะกลับมาเป็นตัวเลือกสำหรับการจัดงานใหม่"}</Typography></ActionDialog>
    <Dialog open={open} onClose={()=>setOpen(false)} maxWidth="md" fullWidth><DialogTitle>{editing ? "รายละเอียดและแก้ไขคนขับ" : "เพิ่มคนขับ"}</DialogTitle><DialogContent dividers><Stack spacing={2} sx={{pt:1}}><Typography variant="body2" color="text.secondary">เลือกพนักงาน ระบุข้อมูลใบขับขี่และประเภทรถที่ขับได้</Typography>{error && <Alert severity="error">{error}</Alert>}<Typography fontWeight={800}>ข้อมูลพนักงาน</Typography><TextField required fullWidth select disabled={Boolean(editing)} label="พนักงาน" value={form.userId} onChange={e=>field("userId",e.target.value)}>{candidates.map(x=><MenuItem key={x.id} value={x.id}>{x.fullName} · {x.employeeCode ?? "-"}</MenuItem>)}</TextField><Grid container spacing={2}>
      <Grid item xs={12}><Typography fontWeight={800}>ใบขับขี่</Typography><Divider sx={{mt:1}} /></Grid>
      <Grid item xs={12} sm={6}><TextField required fullWidth label="เลขที่ใบขับขี่" value={form.licenseNumber} onChange={e=>field("licenseNumber",e.target.value)} /></Grid><Grid item xs={12} sm={6}><TextField required fullWidth label="ประเภทใบขับขี่" value={form.licenseType} onChange={e=>field("licenseType",e.target.value)} /></Grid>
      <Grid item xs={12} sm={6}><AppDatePicker label="วันออกใบขับขี่" value={form.licenseIssueDate} onChange={value=>field("licenseIssueDate",value || null)} /></Grid><Grid item xs={12} sm={6}><AppDatePicker label="วันหมดอายุใบขับขี่" value={form.licenseExpiryDate} onChange={value=>field("licenseExpiryDate",value || null)} error={Boolean(form.licenseIssueDate && form.licenseExpiryDate && form.licenseExpiryDate<form.licenseIssueDate)} helperText={form.licenseIssueDate && form.licenseExpiryDate && form.licenseExpiryDate<form.licenseIssueDate ? "วันหมดอายุต้องไม่ก่อนวันออกใบขับขี่" : undefined} /></Grid>
      <Grid item xs={12}><Typography fontWeight={800}>ประเภทรถที่ขับได้</Typography><Divider sx={{mt:1}} /></Grid>
      {([["canDriveSedan","รถเก๋ง"],["canDrivePickup","รถกระบะ"],["canDriveVan","รถตู้"],["canDriveAmbulance","รถพยาบาล"],["canDriveOther","รถประเภทอื่น"]] as const).map(([key,label])=><Grid item xs={12} sm={4} key={key}><FormControlLabel control={<Switch checked={form[key]} onChange={(_,value)=>field(key,value)} />} label={label} /></Grid>)}
      <Grid item xs={12}><Typography fontWeight={800}>สถานะและหมายเหตุ</Typography><Divider sx={{mt:1}} /></Grid>
      <Grid item xs={12} sm={6}><TextField fullWidth select label="สถานะคนขับ" value={form.driverStatus} onChange={e=>field("driverStatus",e.target.value)}>{driverStatuses.map(([value,label])=><MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField></Grid><Grid item xs={12} sm={6}><FormControlLabel control={<Switch checked={form.isActive} onChange={(_,value)=>field("isActive",value)} />} label="เปิดใช้งาน" /></Grid>
      <Grid item xs={12}><TextField fullWidth multiline minRows={2} label="หมายเหตุ" value={form.note ?? ""} onChange={e=>field("note",e.target.value)} /></Grid>
    </Grid></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>ยกเลิก</Button><Button variant="contained" disabled={save.isPending || !form.userId || !form.licenseNumber.trim() || !form.licenseType.trim() || Boolean(form.licenseIssueDate && form.licenseExpiryDate && form.licenseExpiryDate<form.licenseIssueDate)} onClick={()=>save.mutate()}>บันทึก</Button></DialogActions></Dialog>
  </Stack>;
}

function ManagementToolbar({ title, total, active, actionLabel, onAdd, search, onSearch, searchLabel, statusFilter, onStatusFilter, extraFilters, viewMode, onViewMode }: {
  title: string; total: number; active: number; actionLabel: string; onAdd: () => void;
  search: string; onSearch: (value: string) => void; searchLabel: string;
  statusFilter: string; onStatusFilter: (value: string) => void;
  extraFilters?: ReactNode; viewMode?: "grid"|"list"; onViewMode?: (mode:"grid"|"list") => void;
}) {
  return <Stack spacing={2}>
    <Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between" alignItems={{xs:"stretch",sm:"center"}} spacing={1.5}>
      <Box><Typography variant="h6" fontWeight={800}>{title}</Typography><Typography variant="body2" color="text.secondary">ทั้งหมด {total.toLocaleString("th-TH")} รายการ · เปิดใช้งาน {active.toLocaleString("th-TH")} รายการ</Typography></Box>
      <Button variant="contained" startIcon={<AddOutlinedIcon />} onClick={onAdd} sx={{minHeight:44,whiteSpace:"nowrap",bgcolor:"#164f40","&:hover":{bgcolor:"#0c3b30"}}}>{actionLabel}</Button>
    </Stack>
    <Stack direction={{xs:"column",sm:"row"}} spacing={1.5} alignItems={{sm:"center"}} flexWrap="wrap" useFlexGap>
      <TextField size="small" label={searchLabel} value={search} onChange={e=>onSearch(e.target.value)} sx={{width:{xs:"100%",sm:"auto"},flex:{sm:"1 1 260px"},minWidth:0}} InputProps={{startAdornment:<InputAdornment position="start"><SearchOutlinedIcon fontSize="small" /></InputAdornment>}} />
      {extraFilters}
      <TextField size="small" select label="สถานะการใช้งาน" value={statusFilter} onChange={e=>onStatusFilter(e.target.value)} sx={{minWidth:{sm:190}}}><MenuItem value="all">ทั้งหมด</MenuItem><MenuItem value="active">เปิดใช้งาน</MenuItem><MenuItem value="inactive">ปิดใช้งาน</MenuItem></TextField>
      {viewMode && onViewMode && <Stack direction="row" spacing={.25} aria-label="รูปแบบการแสดงรายการ" sx={{p:.25,border:"1px solid",borderColor:"divider",borderRadius:2,alignSelf:{xs:"flex-start",sm:"center"}}}><Tooltip title="มุมมองการ์ด"><IconButton aria-label="มุมมองการ์ด" size="small" color={viewMode === "grid" ? "primary" : "default"} onClick={()=>onViewMode("grid")}><GridViewOutlinedIcon /></IconButton></Tooltip><Tooltip title="มุมมองรายการ"><IconButton aria-label="มุมมองรายการ" size="small" color={viewMode === "list" ? "primary" : "default"} onClick={()=>onViewMode("list")}><ViewListOutlinedIcon /></IconButton></Tooltip></Stack>}
    </Stack>
  </Stack>;
}

function VehicleCard({item,compact,onEdit,onToggle,toggleDisabled}:{item:FleetVehicleRecord;compact:boolean;onEdit:()=>void;onToggle:()=>void;toggleDisabled:boolean}) {
  const kind = `${item.vehicleTypeName} ${item.brand ?? ""} ${item.model ?? ""}`.toLowerCase();
  const spriteIndex = /ambulance|พยาบาล/.test(kind) ? 0 : /motor|จักรยานยนต์|มอเตอร์ไซค์/.test(kind) ? 7 : /bus|รถบัส/.test(kind) ? 6 : /4x4|4×4/.test(kind) ? 5 : /pickup|กระบะ|truck/.test(kind) ? 3 : /vip|alphard/.test(kind) ? 4 : /van|ตู้/.test(kind) ? 1 : 2;
  const hue = /ambulance|พยาบาล/.test(kind) ? "#dff8eb" : /motor|จักรยานยนต์|มอเตอร์ไซค์/.test(kind) ? "#eee2ff" : /bus|รถบัส/.test(kind) ? "#fde7ef" : /pickup|กระบะ|truck/.test(kind) ? "#ffe8d3" : /van|ตู้/.test(kind) ? "#deecff" : "#e7e8ff";
  return <Card variant="outlined" sx={{height:"100%",borderColor:"#e9dfd1",borderRadius:3,boxShadow:"0 8px 22px rgba(34,70,55,.05)","&:hover":{boxShadow:"0 12px 28px rgba(34,70,55,.12)"}}}><CardContent sx={{height:"100%",display:"flex",flexDirection:compact ? {xs:"column",md:"row"} : "column",gap:1.5,p:2,"&:last-child":{pb:2}}}>
    <Box sx={{flex:compact ? "0 0 210px" : "none",minWidth:0}}><Chip icon={<DirectionsCarOutlinedIcon />} label={item.vehicleTypeName} size="small" sx={{bgcolor:hue,fontWeight:800}} /><Box sx={{height:compact ? 105 : 120,position:"relative",overflow:"hidden"}} role="img" aria-label={`ภาพประกอบประเภทรถ ${item.vehicleTypeName}`}><Box sx={{position:"absolute",width:180,height:180,left:"50%",top:compact ? -37 : -28,transform:"translateX(-50%)",backgroundImage:`url(${spriteIndex === 7 ? wave125Sprite : vehicleSprite})`,backgroundRepeat:"no-repeat",backgroundSize:"400% 200%",backgroundPosition:`${(spriteIndex % 4) * 100 / 3}% ${spriteIndex >= 4 ? 100 : 0}%`,opacity:item.isActive ? 1 : .55}} /></Box></Box>
    <Stack spacing={.75} sx={{flex:1,minWidth:0}}><Stack direction="row" justifyContent="space-between" alignItems="center" spacing={1}><Typography variant="h6" fontWeight={900} sx={{overflowWrap:"anywhere"}}>{item.registrationNumber}</Typography><Chip size="small" label={item.isActive ? "เปิดใช้งาน" : "ปิดใช้งาน"} color={item.isActive ? "success" : "default"} sx={{fontWeight:800,flexShrink:0}} /></Stack><Typography variant="body2" color="text.secondary">รหัส {item.vehicleCode}</Typography><Typography variant="body2" color="text.secondary" sx={{overflowWrap:"anywhere"}}>{[item.brand,item.model].filter(Boolean).join(" ") || "ไม่ระบุยี่ห้อ/รุ่น"}</Typography><Stack direction="row" spacing={1.5} flexWrap="wrap" useFlexGap><Stack direction="row" spacing={.5} alignItems="center"><PeopleOutlineOutlinedIcon sx={{fontSize:16}} /><Typography variant="caption">ผู้โดยสาร {item.passengerCapacity} คน</Typography></Stack><Stack direction="row" spacing={.5} alignItems="center"><SpeedOutlinedIcon sx={{fontSize:16}} /><Typography variant="caption">เลขไมล์ {item.currentMileage.toLocaleString("th-TH")}</Typography></Stack></Stack><Chip size="small" variant="outlined" label={vehicleStatuses.find(([code])=>code===item.status)?.[1] ?? item.status} sx={{alignSelf:"flex-start"}} />
      <Stack direction="row" spacing={1} sx={{pt:1,mt:"auto"}}><Button fullWidth variant="outlined" startIcon={<EditOutlinedIcon />} onClick={onEdit} sx={{minHeight:42,whiteSpace:"nowrap"}}>ดู/แก้ไข</Button><Button fullWidth variant={item.isActive ? "outlined" : "contained"} color={item.isActive ? "error" : "success"} disabled={toggleDisabled} onClick={onToggle} sx={{minHeight:42,whiteSpace:"nowrap"}}>{item.isActive ? "ปิดใช้งาน" : "เปิดใช้งาน"}</Button></Stack>
    </Stack>
  </CardContent></Card>;
}
