import { useEffect, useState } from "react";
import { Alert, Button, Card, CardContent, Chip, MenuItem, Stack, TextField, Typography } from "@mui/material";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { getFleetPermissionDiagnostics, getFleetRolloutStatus, updateFleetRollout } from "../api/fleetApi";
import { PageHeader } from "../components/PageHeader";

export function FleetRolloutAdminPage() {
  const client = useQueryClient(); const status = useQuery({ queryKey: ["fleet-rollout-status"], queryFn: getFleetRolloutStatus }); const diagnostics = useQuery({ queryKey: ["fleet-permission-diagnostics"], queryFn: getFleetPermissionDiagnostics });
  const [mode, setMode] = useState("Disabled"); const [users, setUsers] = useState(""); const [roles, setRoles] = useState(""); const [reason, setReason] = useState("");
  useEffect(() => { if (status.data) { setMode(status.data.mode); setUsers(status.data.uatUserIds.join(", ")); setRoles(status.data.uatRoleCodes.join(", ")); } }, [status.data]);
  const save = useMutation({ mutationFn: () => updateFleetRollout({ mode, uatUserIds: users.split(",").map(x => x.trim()).filter(Boolean), uatRoleCodes: roles.split(",").map(x => x.trim()).filter(Boolean), concurrencyToken: status.data?.concurrencyToken, reason }), onSuccess: () => { setReason(""); void client.invalidateQueries({ queryKey: ["fleet-rollout-status"] }); void client.invalidateQueries({ queryKey: ["fleet-rollout-access"] }); } });
  return <><PageHeader title="Fleet Controlled Rollout" subtitle="เปลี่ยนโหมดแบบมี Audit; ไม่มีการ assign permission ให้ role อัตโนมัติ" />{(status.isError || diagnostics.isError || save.isError) && <Alert severity="error" sx={{ mb: 2 }}>โหลดหรือบันทึกข้อมูลไม่สำเร็จ อาจเกิด concurrency conflict</Alert>}<Stack spacing={2}><Card><CardContent><Stack spacing={2}><Stack direction="row" spacing={1} alignItems="center"><Typography>สถานะปัจจุบัน</Typography><Chip label={status.data?.mode ?? "Loading"} color={status.data?.mode === "Enabled" ? "success" : status.data?.mode === "UATOnly" ? "warning" : "default"} /></Stack><TextField select label="Rollout Mode" value={mode} onChange={e => setMode(e.target.value)}>{["Disabled", "UATOnly", "Enabled"].map(x => <MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField label="UAT User IDs (comma-separated)" value={users} onChange={e => setUsers(e.target.value)} /><TextField label="UAT Role Codes (comma-separated)" value={roles} onChange={e => setRoles(e.target.value)} /><TextField required label="เหตุผลการเปลี่ยน" value={reason} onChange={e => setReason(e.target.value)} /><Button variant="contained" disabled={!reason.trim() || save.isPending} onClick={() => { if (window.confirm(`ยืนยันเปลี่ยน Fleet rollout เป็น ${mode}?`)) save.mutate(); }}>{save.isPending ? "กำลังบันทึก..." : "บันทึก Rollout"}</Button></Stack></CardContent></Card><Card><CardContent><Typography variant="h6">Permission Diagnostics</Typography>{diagnostics.isLoading ? <Typography>กำลังโหลด...</Typography> : <Typography component="pre" sx={{ whiteSpace: "pre-wrap", overflow: "auto" }}>{JSON.stringify(diagnostics.data, null, 2)}</Typography>}</CardContent></Card></Stack></>;
}
