/* eslint-disable react-hooks/exhaustive-deps */
import { useEffect,useState } from "react";
import { Alert,Button,Card,CardContent,Chip,MenuItem,Stack,TextField,Typography } from "@mui/material";
import { Link,useNavigate,useParams } from "react-router-dom";
import { emergencyAction,getEmergencyReview,getEmergencyReviews,type EmergencyReviewItem } from "../api/fleetApi";

export function FleetEmergencyReviewQueuePage(){const[rows,setRows]=useState<EmergencyReviewItem[]>([]);const[status,setStatus]=useState("PENDING");const[search,setSearch]=useState("");const[error,setError]=useState("");const[loading,setLoading]=useState(true);const load=async()=>{setLoading(true);setError("");try{setRows((await getEmergencyReviews({search:search||undefined,status})).items)}catch{setError("โหลดคิว post-review ไม่สำเร็จ")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);return <Stack spacing={2}><Typography variant="h4">Emergency Post-Review</Typography><Alert severity="warning">Internal Fleet transport only — ไม่ใช่ EMS/1669 และไม่มี clinical triage</Alert><Stack direction={{xs:"column",sm:"row"}} spacing={1}><TextField label="ค้นหา" value={search} onChange={e=>setSearch(e.target.value)} fullWidth/><TextField select label="สถานะ" value={status} onChange={e=>setStatus(e.target.value)} sx={{minWidth:160}}><MenuItem value="PENDING">รอทบทวน</MenuItem><MenuItem value="COMPLETED">ทบทวนแล้ว</MenuItem></TextField><Button onClick={()=>void load()}>ค้นหา</Button></Stack>{loading&&<Typography>กำลังโหลด…</Typography>}{error&&<Alert severity="error" action={<Button onClick={()=>void load()}>ลองใหม่</Button>}>{error}</Alert>}{!loading&&!error&&rows.length===0&&<Alert severity="info">ไม่มีรายการ</Alert>}{rows.map(x=><Card key={x.id}><CardContent><Stack direction={{xs:"column",sm:"row"}} justifyContent="space-between"><div><Stack direction="row" gap={1}><Typography variant="h6">{x.requestNo}</Typography>{x.slaBreached&&<Chip color="error" label="SLA BREACH"/>}{x.bypassUsed&&<Chip color="warning" label="BYPASS"/>}</Stack><Typography>{x.emergencyPolicyCode} · เป้าหมาย {x.responseTargetMinutes} นาที</Typography></div><Button component={Link} to={`/fleet/emergency/${x.id}/post-review`}>{x.requiresPostReview?"ทบทวน":"ดูผล"}</Button></Stack></CardContent></Card>)}</Stack>}

export function FleetEmergencyPostReviewPage(){const{id}=useParams();const nav=useNavigate();const[data,setData]=useState<Record<string,unknown>|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[form,setForm]=useState({outcome:"ACCEPTABLE",wasBypassAppropriate:false,responseTimeAssessment:"",safetyIssues:"",followUpActions:"",notes:""});useEffect(()=>{void getEmergencyReview(id!).then(setData).catch(()=>setError("โหลดข้อมูลไม่สำเร็จ"))},[id]);const submit=async()=>{setBusy(true);setError("");try{await emergencyAction(id!,"post-review",{...form,concurrencyToken:data?.concurrencyToken});nav("/fleet/emergency/review")}catch{setError("บันทึกไม่สำเร็จหรือข้อมูลถูกเปลี่ยน กรุณาโหลดใหม่")}finally{setBusy(false)}};if(!data&&!error)return <Typography>กำลังโหลด…</Typography>;return <Stack spacing={2}><Typography variant="h4">Post-Review {String(data?.requestNo??"")}</Typography>{error&&<Alert severity="error">{error}</Alert>}<Alert severity="info">Policy {String(data?.emergencyPolicyCode??"-")} · Emergency reason: {String(data?.emergencyReason??"-")}</Alert><TextField select label="Outcome" value={form.outcome} onChange={e=>setForm(x=>({...x,outcome:e.target.value}))}>{["ACCEPTABLE","NEEDS_IMPROVEMENT","POLICY_VIOLATION"].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</TextField><TextField select label="Bypass appropriate" value={String(form.wasBypassAppropriate)} onChange={e=>setForm(x=>({...x,wasBypassAppropriate:e.target.value==="true"}))}><MenuItem value="true">เหมาะสม</MenuItem><MenuItem value="false">ไม่เหมาะสม/ไม่ได้ใช้</MenuItem></TextField>{(["responseTimeAssessment","safetyIssues","followUpActions","notes"] as const).map(k=><TextField key={k} multiline label={k} value={form[k]} onChange={e=>setForm(x=>({...x,[k]:e.target.value}))}/>)}<Button variant="contained" disabled={busy} onClick={()=>{if(window.confirm("ยืนยันผล post-review? บันทึกนี้เป็น immutable"))void submit()}}>บันทึกผล</Button></Stack>}
