using Hop.Api.Data;
using Hop.Api.Models;
using Hop.Api.Services;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using Xunit;

namespace Hop.Api.Tests;

[Collection("FleetPostgreSql")]
public sealed class FleetM42PostgreSqlIntegrationTests
{
    [Fact,Trait("Category","FleetM42PostgreSqlIntegration")]
    public async Task Migration_has_policy_snapshots_constraints_and_no_production_role_mapping()
    {await using var db=await Database();var history=await db.Database.SqlQueryRaw<string>("select \"MigrationId\" as \"Value\" from \"__EFMigrationsHistory\" order by \"MigrationId\"").ToListAsync();Assert.Contains(history,x=>x.Contains("CompleteFleetM42Uat"));Assert.True(await db.FleetEmergencyPolicies.AnyAsync(x=>x.Code=="INTERNAL_EMERGENCY_DEFAULT"));Assert.Equal(0,await db.RolePermissions.CountAsync(x=>x.Permission!.Code.StartsWith("Fleet")));}

    [Fact,Trait("Category","FleetM42PostgreSqlIntegration")]
    public async Task Typed_compatibility_persists_match_partial_not_match_and_immutable_override()
    {await using var db=await Database();var d=new Department{Name="m42-d"};var u=User("u",d);var type=new FleetVehicleType{Code="M42",Name="M42"};var v=new FleetVehicle{VehicleCode="M42-V",RegistrationNumber="M42-V",VehicleType=type,SeatCapacityTotal=4,PassengerCapacity=3};var r=Request(u,d);var b=Cap("B",FleetCapabilityDataTypes.Boolean,false);var n=Cap("N",FleetCapabilityDataTypes.Number,false);var s=Cap("S",FleetCapabilityDataTypes.Boolean,true);db.AddRange(d,u,type,v,r,b,n,s,new FleetVehicleCapability{Vehicle=v,Capability=b,BooleanValue=true,CreatedByUserId=u.Id},new FleetVehicleCapability{Vehicle=v,Capability=n,NumericValue=5,CreatedByUserId=u.Id},new FleetVehicleCapability{Vehicle=v,Capability=s,BooleanValue=false,CreatedByUserId=u.Id},new FleetRequestRequiredCapability{FleetRequest=r,Capability=b,Operator=FleetCapabilityOperators.Equals,RequiredBooleanValue=true,IsMandatory=true},new FleetRequestRequiredCapability{FleetRequest=r,Capability=n,Operator=FleetCapabilityOperators.GreaterThanOrEqual,RequiredNumericValue=10,IsMandatory=false},new FleetRequestRequiredCapability{FleetRequest=r,Capability=s,Operator=FleetCapabilityOperators.Equals,RequiredBooleanValue=true,IsMandatory=true});await db.SaveChangesAsync();var service=new FleetCompatibilityService(db);var before=await service.EvaluateAsync(r.Id,v.Id,DateTime.UtcNow,default);Assert.Equal(FleetCompatibilityStatuses.NotMatch,before.Status);var o=new FleetCompatibilityOverride{FleetRequestId=r.Id,VehicleId=v.Id,MismatchCapabilityIds=$"[\"{n.Id}\"]",Reason="QA reason",ApprovedByUserId=u.Id};db.Add(o);await db.SaveChangesAsync();var after=await service.EvaluateAsync(r.Id,v.Id,DateTime.UtcNow,default);Assert.Contains(after.Capabilities,x=>x.CapabilityId==n.Id&&x.Status==FleetCompatibilityStatuses.Overridden);Assert.Contains(after.Capabilities,x=>x.CapabilityId==s.Id&&x.Status==FleetCompatibilityStatuses.NotMatch);Assert.Equal("QA reason",(await db.FleetCompatibilityOverrides.AsNoTracking().SingleAsync()).Reason);}

    [Fact,Trait("Category","FleetM42PostgreSqlIntegration")]
    public async Task PostgreSQL_rejects_duplicate_active_binding_and_preserves_timestamptz_snapshot()
    {await using var db=await Database();var d=new Department{Name="m42-x"};var u=User("x",d);var t=new FleetVehicleType{Code="X",Name="X"};var v=new FleetVehicle{VehicleCode="X",RegistrationNumber="X",VehicleType=t,SeatCapacityTotal=2,PassengerCapacity=1};var c=Cap("X",FleetCapabilityDataTypes.Boolean,false);db.AddRange(d,u,t,v,c,new FleetVehicleCapability{Vehicle=v,Capability=c,BooleanValue=true,CreatedByUserId=u.Id},new FleetVehicleCapability{Vehicle=v,Capability=c,BooleanValue=false,CreatedByUserId=u.Id});await Assert.ThrowsAsync<DbUpdateException>(()=>db.SaveChangesAsync());}

    [Fact,Trait("Category","FleetM42PostgreSqlIntegration")]
    public async Task Emergency_policy_queue_snapshot_post_review_and_sla_are_persisted_in_PostgreSQL()
    {
        await using var db=await Database();var d=new Department{Name="m42-emergency"};var u=User("emergency",d);var fixedAt=new DateTime(2026,8,2,2,0,0,DateTimeKind.Utc);var policy=new FleetEmergencyPolicy{Code="M42-EM",Name="M42 Emergency",Priority=FleetPriorities.Emergency,ResponseTargetMinutes=15,DispatchTargetMinutes=10,DriverAcknowledgementTargetMinutes=5,ApprovalBypassAllowed=true,PostReviewRequired=true,EffectiveFrom=fixedAt.AddDays(-1),CreatedByUserId=u.Id};
        FleetRequest Item(string no,string priority,DateTime submitted,string status)=>new(){RequestNo=no,RequesterUser=u,RequesterDepartment=d,RequestDate=new DateOnly(2026,8,2),Purpose=no,MissionType="QA",Destination="QA",ContactPersonName="QA",ContactPhone="0000",DepartureAt=fixedAt.AddHours(2),ExpectedReturnAt=fixedAt.AddHours(3),PassengerCount=1,Priority=priority,Status=status,SubmittedAt=submitted,EmergencyReason=priority==FleetPriorities.Emergency?"Emergency":null,ReportedByUserId=priority==FleetPriorities.Emergency?u.Id:null,ReportedAt=priority==FleetPriorities.Emergency?submitted:null,IncidentLocation=priority==FleetPriorities.Emergency?"QA":null,EmergencyPolicy=priority==FleetPriorities.Emergency?policy:null,EmergencyPolicyCode=priority==FleetPriorities.Emergency?policy.Code:null,ResponseTargetMinutesSnapshot=priority==FleetPriorities.Emergency?15:null,DispatchTargetMinutesSnapshot=priority==FleetPriorities.Emergency?10:null,DriverAcknowledgementTargetMinutesSnapshot=priority==FleetPriorities.Emergency?5:null,ApprovalBypassAllowedSnapshot=priority==FleetPriorities.Emergency?true:null,PostReviewRequiredSnapshot=priority==FleetPriorities.Emergency?true:null,RequiresPostReview=priority==FleetPriorities.Emergency,CreatedByUserId=u.Id};
        var emergency=Item("VH-EM-1",FleetPriorities.Emergency,fixedAt.AddMinutes(-20),FleetRequestStatuses.Completed);var urgent=Item("VH-UR-1",FleetPriorities.Urgent,fixedAt.AddMinutes(-30),FleetRequestStatuses.PendingDispatch);var normal=Item("VH-NO-1",FleetPriorities.Normal,fixedAt.AddMinutes(-40),FleetRequestStatuses.PendingDispatch);var review=new FleetEmergencyPostReview{FleetRequest=emergency,ReviewedByUserId=u.Id,Outcome=FleetEmergencyReviewOutcomes.Acceptable,WasBypassAppropriate=true,ResponseTimeAssessment="SLA breach documented"};db.AddRange(d,u,policy,emergency,urgent,normal,review);await db.SaveChangesAsync();
        var queue=await db.FleetRequests.AsNoTracking().Where(x=>x.Status==FleetRequestStatuses.PendingDispatch).OrderBy(x=>x.Priority==FleetPriorities.Emergency?0:x.Priority==FleetPriorities.Urgent?1:2).ThenBy(x=>x.SubmittedAt).Select(x=>x.RequestNo).ToListAsync();Assert.Equal(new[]{"VH-UR-1","VH-NO-1"},queue);var stored=await db.FleetRequests.AsNoTracking().SingleAsync(x=>x.Id==emergency.Id);Assert.Equal(15,stored.ResponseTargetMinutesSnapshot);Assert.True(stored.PostReviewRequiredSnapshot);Assert.True(stored.SubmittedAt!.Value.Kind==DateTimeKind.Utc);Assert.True(await db.FleetEmergencyPostReviews.AnyAsync(x=>x.FleetRequestId==emergency.Id&&x.Outcome==FleetEmergencyReviewOutcomes.Acceptable));Assert.True(fixedAt>stored.SubmittedAt.Value.AddMinutes(stored.ResponseTargetMinutesSnapshot!.Value));
    }

    [Fact,Trait("Category","FleetM42PostgreSqlIntegration")]
    public async Task Mobile_driver_assignment_trip_mileage_attachment_idempotency_and_replacement_are_persisted_in_PostgreSQL()
    {
        await using var db=await Database();var d=new Department{Name="m42-mobile"};var driver=User("driver",d);var previous=User("previous",d);var dispatcher=User("dispatcher",d);var type=new FleetVehicleType{Code="MOB",Name="Mobile"};var vehicle=new FleetVehicle{VehicleCode="MOB-1",RegistrationNumber="MOB-1",VehicleType=type,SeatCapacityTotal=4,PassengerCapacity=3,CurrentMileage=1040};var request=Request(driver,d);request.RequestNo="VH-MOB-1";request.Status=FleetRequestStatuses.InProgress;var oldAssignment=new FleetAssignment{FleetRequest=request,Vehicle=vehicle,DriverUser=previous,AssignedByUser=dispatcher,IsActive=false,AssignmentStatus=FleetAssignmentStatuses.Replaced};var active=new FleetAssignment{FleetRequest=request,Vehicle=vehicle,DriverUser=driver,AssignedByUser=dispatcher,IsActive=true,AssignmentStatus=FleetAssignmentStatuses.Assigned,ReplacedAssignment=oldAssignment,AssignmentReason="Driver replacement"};var trip=new FleetTripRecord{FleetRequest=request,Assignment=active,DriverUser=driver,ActualStartAt=DateTime.UtcNow,StartMileage=1040,StartIdempotencyKey="m42-start"};var attachment=new FleetTripAttachment{Trip=trip,OriginalFileName="evidence.pdf",StoredFileName="m42.pdf",ContentType="application/pdf",FilePath="fleet/trips/m42.pdf",FileSize=3,IdempotencyKey="m42-attachment",CreatedByUserId=driver.Id};db.AddRange(d,driver,previous,dispatcher,type,vehicle,request,oldAssignment,active,trip,attachment);await db.SaveChangesAsync();
        var stored=await db.FleetTripRecords.AsNoTracking().SingleAsync(x=>x.Id==trip.Id);Assert.Equal(1040,stored.StartMileage);Assert.True(stored.StartMileage>=vehicle.CurrentMileage);Assert.Equal(driver.Id,stored.DriverUserId);Assert.True(await db.FleetAssignments.AnyAsync(x=>x.Id==oldAssignment.Id&&!x.IsActive&&x.AssignmentStatus==FleetAssignmentStatuses.Replaced));Assert.True(await db.FleetAssignments.AnyAsync(x=>x.Id==active.Id&&x.IsActive&&x.ReplacedAssignmentId==oldAssignment.Id));Assert.True(await db.FleetTripAttachments.AnyAsync(x=>x.TripId==trip.Id&&x.IdempotencyKey=="m42-attachment"&&!x.IsDeleted));
        db.FleetTripAttachments.Add(new(){TripId=trip.Id,OriginalFileName="duplicate.pdf",StoredFileName="duplicate.pdf",ContentType="application/pdf",FilePath="fleet/trips/duplicate.pdf",FileSize=1,IdempotencyKey="m42-attachment",CreatedByUserId=driver.Id});await Assert.ThrowsAsync<DbUpdateException>(()=>db.SaveChangesAsync());
    }

    private static async Task<AppDbContext> Database(){var connection=Environment.GetEnvironmentVariable("HOP_E2E_CONNECTION_STRING");if(string.IsNullOrWhiteSpace(connection))throw new InvalidOperationException("HOP_E2E_CONNECTION_STRING is required for FleetM42PostgreSqlIntegration.");var cs=new NpgsqlConnectionStringBuilder(connection);if(!new[]{"qa","test","uat","ci","integration"}.Any(x=>cs.Database.Contains(x,StringComparison.OrdinalIgnoreCase)))throw new InvalidOperationException("Refusing non-test database.");var db=new AppDbContext(new DbContextOptionsBuilder<AppDbContext>().UseNpgsql(connection).Options);await db.Database.EnsureDeletedAsync();await db.Database.MigrateAsync();return db;}
    private static User User(string x,Department d)=>new(){Id=Guid.NewGuid(),EmployeeCode=$"m42-{x}",Username=$"m42-{x}",FullName="M42",PasswordHash="x",Department=d};
    private static FleetCapability Cap(string x,string type,bool safety)=>new(){Code=$"M42-{x}",Name=x,DataType=type,IsRequiredSafetyCapability=safety};
    private static FleetRequest Request(User u,Department d)=>new(){RequestNo="VH-M42-1",RequesterUser=u,RequesterDepartment=d,RequestDate=new DateOnly(2026,8,2),Purpose="M42",MissionType="QA",Destination="QA",ContactPersonName="QA",ContactPhone="0",DepartureAt=DateTime.UtcNow.AddHours(1),ExpectedReturnAt=DateTime.UtcNow.AddHours(2),PassengerCount=1,CreatedByUserId=u.Id};
}
