using System.Text.Json;
using Hop.Api.Authorization;
using Hop.Api.Data;
using Hop.Api.Models;
using Microsoft.EntityFrameworkCore;
using Npgsql;

var command = args.FirstOrDefault() ?? ""; var manifestPath = args.Skip(1).FirstOrDefault() ?? "tmp/fleet-m4.1-fixture.json";
var connection = Environment.GetEnvironmentVariable("FLEET_QA_CONNECTION_STRING") ?? throw new InvalidOperationException("FLEET_QA_CONNECTION_STRING is required.");
var environment = Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") ?? "Development"; var cs = new NpgsqlConnectionStringBuilder(connection);
if (environment.Equals("Production", StringComparison.OrdinalIgnoreCase)) throw new InvalidOperationException("QA tooling is disabled in Production.");
if (!string.Equals(Environment.GetEnvironmentVariable("FLEET_QA_ENABLED"), "true", StringComparison.OrdinalIgnoreCase)) throw new InvalidOperationException("QA tooling feature flag is disabled.");
if (!new[] { "qa", "test", "uat", "ci" }.Any(x => (cs.Database ?? "").Contains(x, StringComparison.OrdinalIgnoreCase))) throw new InvalidOperationException("QA database name must contain qa, test, uat, or ci.");
var options = new DbContextOptionsBuilder<AppDbContext>().UseNpgsql(connection).Options; await using var db = new AppDbContext(options); await db.Database.MigrateAsync();
var jsonOptions = new JsonSerializerOptions { WriteIndented = true, PropertyNamingPolicy = JsonNamingPolicy.CamelCase, PropertyNameCaseInsensitive = true };
if (command == "create") { var result = await Create(db); Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(manifestPath))!); await File.WriteAllTextAsync(manifestPath, JsonSerializer.Serialize(result, jsonOptions)); Console.WriteLine($"Fleet QA fixture created. RunId={result.RunId} Manifest={Path.GetFullPath(manifestPath)}"); }
else if (command == "cleanup") { var manifest = JsonSerializer.Deserialize<QaManifest>(await File.ReadAllTextAsync(manifestPath), jsonOptions) ?? throw new InvalidOperationException("Invalid fixture manifest."); await Cleanup(db, manifest); Console.WriteLine($"Fleet QA fixture cleaned. RunId={manifest.RunId}"); }
else throw new InvalidOperationException("Use: create <manifest> or cleanup <manifest>.");

static async Task<QaManifest> Create(AppDbContext db)
{
    var fixedAt = new DateTime(2026, 8, 1, 0, 0, 0, DateTimeKind.Utc); var runId = $"qa-{DateTime.UtcNow:yyyyMMddHHmmss}-{Guid.NewGuid():N}"[..31]; var department = new Department { Name = $"{runId}-department", Description = "Automated Fleet QA only" }; db.Add(department);
    var permissionCodes = new[] { FleetPermissions.RequestViewOwn,FleetPermissions.RequestCreate,FleetPermissions.RequestEditOwn,FleetPermissions.DashboardView, FleetPermissions.ReportView, FleetPermissions.ReportExport, FleetPermissions.CalendarView, FleetPermissions.MaintenanceView, FleetPermissions.MaintenanceManage, FleetPermissions.MaintenanceComplete, FleetPermissions.MaintenanceCancel, FleetPermissions.MaintenanceOverrideMileage, FleetPermissions.MaintenanceManageDocuments, FleetPermissions.MaintenanceUploadAttachment, FleetPermissions.VehicleManage, FleetPermissions.DispatchView, FleetPermissions.DispatchAssign, FleetPermissions.DriverViewOwnJobs, FleetPermissions.DriverAcknowledge, FleetPermissions.DriverStart, FleetPermissions.DriverComplete, FleetPermissions.TripUploadAttachment, FleetPermissions.CapabilityView, FleetPermissions.CapabilityManage, FleetPermissions.VehicleCapabilityManage, FleetPermissions.RequestCapabilityManageOwn, FleetPermissions.CompatibilityView, FleetPermissions.CompatibilityOverride, FleetPermissions.EmergencyCreate, FleetPermissions.EmergencyViewOwn, FleetPermissions.EmergencyViewQueue, FleetPermissions.EmergencyDispatch, FleetPermissions.EmergencyBypassApproval, FleetPermissions.EmergencyReview, FleetPermissions.EmergencyViewAudit, FleetPermissions.EmergencyPolicyView, FleetPermissions.EmergencyPolicyManage };
    permissionCodes = permissionCodes.Concat([FleetPermissions.RequestSubmit,FleetPermissions.AdminReviewApprove,FleetPermissions.AdminReviewReturn,FleetPermissions.AdminReviewReject,FleetPermissions.DirectorApprove,FleetPermissions.DirectorReturn,FleetPermissions.DirectorReject,FleetPermissions.SettingsManage]).Distinct().ToArray();
    var existing = await db.Permissions.Where(x => permissionCodes.Contains(x.Code)).ToDictionaryAsync(x => x.Code); foreach (var code in permissionCodes.Where(x => !existing.ContainsKey(x))) { var p = new Permission { Code = code, Name = code, Group = "FleetQA", Action = "Test" }; db.Add(p); existing[code] = p; }
    var passwords = new Dictionary<string, string> { { "admin", Required("FLEET_QA_ADMIN_PASSWORD") }, { "dashboard", Required("FLEET_QA_DASHBOARD_PASSWORD") }, { "noOverride", Required("FLEET_QA_NO_OVERRIDE_PASSWORD") }, { "driver", Required("FLEET_QA_DRIVER_PASSWORD") }, { "previousDriver", Required("FLEET_QA_PREVIOUS_DRIVER_PASSWORD") }, { "requester", Required("FLEET_QA_REQUESTER_PASSWORD") }, { "dispatcher", Required("FLEET_QA_DISPATCHER_PASSWORD") }, { "reviewer", Required("FLEET_QA_REVIEWER_PASSWORD") }, { "director", Required("FLEET_QA_DIRECTOR_PASSWORD") } };
    var users = new Dictionary<string, User>(); foreach (var key in new[] { "admin", "dashboard", "noOverride", "driver", "previousDriver", "requester", "dispatcher", "reviewer", "director" }) { var password = passwords.GetValueOrDefault(key, passwords["admin"]); var user = new User { EmployeeCode = $"{runId}-{key}", Username = $"{runId}-{key}", FullName = $"Fleet QA {key}", PasswordHash = BCrypt.Net.BCrypt.HashPassword(password), Department = department, IsActive = true }; var role = new Role { Name = $"{runId}-{key}", Description = "Automated Fleet QA role" }; db.AddRange(user, role); db.UserRoles.Add(new UserRole { User = user, Role = role }); foreach (var code in Permissions(key, permissionCodes)) db.RolePermissions.Add(new RolePermission { Role = role, Permission = existing[code] }); users[key] = user; }
    var vehicleType = new FleetVehicleType { Code = $"QA{Guid.NewGuid():N}"[..12].ToUpperInvariant(), Name = $"{runId} type", IsActive = true }; var vehicle = new FleetVehicle { VehicleCode = $"QA-{runId[^8..]}", RegistrationNumber = $"QA-{Guid.NewGuid():N}"[..14], VehicleType = vehicleType, SeatCapacityTotal = 8, PassengerCapacity = 7, CurrentMileage = 1000, Status = FleetVehicleStatuses.Available, IsActive = true, OwningDepartment = department, ResponsibleUser = users["admin"] }; var attachmentVehicle = new FleetVehicle { VehicleCode = $"AT-{runId[^8..]}", RegistrationNumber = $"AT-{Guid.NewGuid():N}"[..14], VehicleType = vehicleType, SeatCapacityTotal = 8, PassengerCapacity = 7, CurrentMileage = 2000, Status = FleetVehicleStatuses.InUse, IsActive = true, OwningDepartment = department, ResponsibleUser = users["admin"] }; db.AddRange(vehicleType, vehicle, attachmentVehicle);
    var driver = new FleetDriverProfile { User = users["driver"], LicenseNumber = $"QA-{Guid.NewGuid():N}", LicenseType = "QA", LicenseExpiryDate = new DateOnly(2030, 1, 1), CanDriveVan = true, CanDriveSedan = true, DriverStatus = FleetDriverStatuses.Available, IsActive = true };
    var previousDriver = new FleetDriverProfile { User = users["previousDriver"], LicenseNumber = $"QA-{Guid.NewGuid():N}", LicenseType = "QA", LicenseExpiryDate = new DateOnly(2030, 1, 1), CanDriveVan = true, CanDriveSedan = true, DriverStatus = FleetDriverStatuses.Available, IsActive = true }; db.AddRange(driver, previousDriver);
    var maintenanceType = new FleetMaintenanceType { Code = $"QA-{Guid.NewGuid():N}"[..14], Name = $"{runId} inspection", Category = "Inspection", IsDateBased = true, IsMileageBased = true, BlocksAvailabilityWhenOverdue = true, CreatedByUserId = users["admin"].Id }; var schedule = new FleetVehicleMaintenanceSchedule { Vehicle = vehicle, MaintenanceType = maintenanceType, DueDate = fixedAt.AddHours(18), DueMileage = 1100, Status = FleetMaintenanceStatuses.Active, CreatedByUserId = users["admin"].Id }; db.AddRange(maintenanceType, schedule);
    var request = new FleetRequest { RequestNo = $"VH-QA-{Guid.NewGuid():N}"[..20], RequesterUser = users["requester"], RequesterDepartment = department, RequestDate = new DateOnly(2026, 8, 1), Purpose = "Automated QA", MissionType = "QA", Destination = "QA Destination", ContactPersonName = "QA", ContactPhone = "000", DepartureAt = fixedAt.AddHours(8), ExpectedReturnAt = fixedAt.AddHours(14), PassengerCount = 1, Status = FleetRequestStatuses.Completed, CreatedByUserId = users["requester"].Id, CreatedAt = fixedAt }; var assignment = new FleetAssignment { FleetRequest = request, Vehicle = vehicle, DriverUser = users["driver"], AssignedByUser = users["dispatcher"], AssignedAt = fixedAt.AddHours(7), IsActive = false, AssignmentStatus = FleetAssignmentStatuses.Completed }; var trip = new FleetTripRecord { FleetRequest = request, Assignment = assignment, DriverUser = users["driver"], ActualStartAt = fixedAt.AddHours(9), ActualEndAt = fixedAt.AddHours(13), StartMileage = 1000, EndMileage = 1040 }; db.AddRange(request, assignment, trip);
    db.FleetVehicleUnavailability.Add(new FleetVehicleUnavailability { Vehicle = vehicle, StartAt = fixedAt.AddHours(14), EndAt = fixedAt.AddHours(18), Reason = "QA overlap", Type = FleetVehicleUnavailabilityTypes.Other, CreatedByUser = users["admin"] }); db.FleetDriverUnavailability.Add(new FleetDriverUnavailability { User = users["driver"], StartAt = fixedAt.AddHours(20), EndAt = fixedAt.AddHours(22), Reason = "QA unavailable", CreatedByUser = users["admin"] });
    var inProgress = new FleetVehicleMaintenanceSchedule { Vehicle = vehicle, MaintenanceType = maintenanceType, Status = FleetMaintenanceStatuses.InProgress, DueDate = fixedAt.AddHours(16), CreatedAt = fixedAt.AddHours(16), UpdatedAt = fixedAt.AddHours(16), CreatedByUserId = users["admin"].Id }; db.Add(inProgress); db.FleetVehicleMaintenanceRecords.Add(new FleetVehicleMaintenanceRecord { VehicleId = vehicle.Id, Schedule = inProgress, MaintenanceTypeId = maintenanceType.Id, StartedAt = fixedAt.AddHours(16), StartMileage = 1040, CreatedByUserId = users["admin"].Id });
    var document = new FleetVehicleDocument { Vehicle = vehicle, DocumentType = "INSURANCE", DocumentNumber = $"QA-{Guid.NewGuid():N}", IssuedAt = fixedAt.AddMonths(-1), ExpiresAt = fixedAt.AddHours(23), IsRequired = true, CreatedByUserId = users["admin"].Id }; var cancellation = new FleetCancellationRequest { FleetRequest = request, RequestedByUser = users["requester"], PreviousStatus = FleetRequestStatuses.Ready, Reason = "QA cancellation", Status = "APPROVED", CreatedAt = fixedAt.AddHours(6), CompletedAt = fixedAt.AddHours(7), ReviewedByUser = users["director"] }; var rollout = new FleetRolloutSetting { Mode = "Enabled", CreatedAt = DateTime.UtcNow }; db.AddRange(document, cancellation, rollout);
    var capability=new FleetCapability{Code=$"M42-{runId[^8..]}",Name=$"{runId} lift",Category="ACCESSIBILITY",DataType=FleetCapabilityDataTypes.Boolean,IsActive=true,CreatedByUserId=users["admin"].Id};var mismatchCapability=new FleetCapability{Code=$"MIS-{runId[^8..]}",Name=$"{runId} optional equipment",Category="GENERAL",DataType=FleetCapabilityDataTypes.Boolean,IsActive=true,CreatedByUserId=users["admin"].Id};var safetyCapability=new FleetCapability{Code=$"SAFE-{runId[^8..]}",Name=$"{runId} safety",Category="SAFETY",DataType=FleetCapabilityDataTypes.Boolean,IsRequiredSafetyCapability=true,IsActive=true,CreatedByUserId=users["admin"].Id};var policy=new FleetEmergencyPolicy{Code=$"POL-{runId[^8..]}",Name=$"{runId} emergency",Priority=FleetPriorities.Emergency,ResponseTargetMinutes=15,DispatchTargetMinutes=10,DriverAcknowledgementTargetMinutes=5,ApprovalBypassAllowed=true,PostReviewRequired=true,IsActive=true,EffectiveFrom=fixedAt.AddDays(-1),CreatedByUserId=users["admin"].Id};db.AddRange(capability,mismatchCapability,safetyCapability,policy);db.FleetVehicleCapabilities.AddRange(new FleetVehicleCapability{Vehicle=vehicle,Capability=capability,BooleanValue=true,EffectiveFrom=fixedAt.AddDays(-1),CreatedByUserId=users["admin"].Id},new FleetVehicleCapability{Vehicle=vehicle,Capability=mismatchCapability,BooleanValue=false,EffectiveFrom=fixedAt.AddDays(-1),CreatedByUserId=users["admin"].Id},new FleetVehicleCapability{Vehicle=vehicle,Capability=safetyCapability,BooleanValue=false,EffectiveFrom=fixedAt.AddDays(-1),CreatedByUserId=users["admin"].Id});db.FleetRequestRequiredCapabilities.AddRange(new FleetRequestRequiredCapability{FleetRequest=request,Capability=capability,Operator=FleetCapabilityOperators.Equals,RequiredBooleanValue=true,IsMandatory=true},new FleetRequestRequiredCapability{FleetRequest=request,Capability=mismatchCapability,Operator=FleetCapabilityOperators.Equals,RequiredBooleanValue=true,IsMandatory=true},new FleetRequestRequiredCapability{FleetRequest=request,Capability=safetyCapability,Operator=FleetCapabilityOperators.Equals,RequiredBooleanValue=true,IsMandatory=true});request.Priority=FleetPriorities.Emergency;request.EmergencyReason="QA emergency";request.ReportedByUserId=users["requester"].Id;request.ReportedAt=fixedAt.AddHours(6);request.IncidentLocation="QA origin";request.EmergencyPolicy=policy;request.EmergencyPolicyCode=policy.Code;request.ResponseTargetMinutesSnapshot=15;request.DispatchTargetMinutesSnapshot=10;request.DriverAcknowledgementTargetMinutesSnapshot=5;request.ApprovalBypassAllowedSnapshot=true;request.PostReviewRequiredSnapshot=true;request.RequiresPostReview=true;request.SubmittedAt=fixedAt.AddHours(6);
    var emergencyQueueRequest=new FleetRequest{RequestNo=$"VH-EQ-{Guid.NewGuid():N}"[..20],RequesterUser=users["requester"],RequesterDepartment=department,RequestDate=new DateOnly(2026,8,1),Purpose="M4.2 emergency queue",MissionType="QA",Destination="QA Emergency",ContactPersonName="QA",ContactPhone="0000",DepartureAt=fixedAt.AddHours(10),ExpectedReturnAt=fixedAt.AddHours(12),PassengerCount=1,Status=FleetRequestStatuses.PendingDispatch,Priority=FleetPriorities.Emergency,EmergencyReason="M4.2 queue",ReportedByUserId=users["requester"].Id,ReportedAt=fixedAt.AddHours(5),IncidentLocation="QA queue origin",EmergencyPolicy=policy,EmergencyPolicyCode=policy.Code,ResponseTargetMinutesSnapshot=15,DispatchTargetMinutesSnapshot=10,DriverAcknowledgementTargetMinutesSnapshot=5,ApprovalBypassAllowedSnapshot=true,PostReviewRequiredSnapshot=true,RequiresPostReview=true,SubmittedAt=fixedAt.AddHours(5),CreatedByUserId=users["requester"].Id,CreatedAt=fixedAt};
    var driverRequest=new FleetRequest{RequestNo=$"VH-DR-{Guid.NewGuid():N}"[..20],RequesterUser=users["requester"],RequesterDepartment=department,RequestDate=new DateOnly(2026,8,1),Purpose="M4.2 driver mobile",MissionType="QA",Destination="QA Driver",ContactPersonName="QA",ContactPhone="0000",DepartureAt=fixedAt.AddHours(9),ExpectedReturnAt=fixedAt.AddHours(11),PassengerCount=1,Status=FleetRequestStatuses.InProgress,Priority=FleetPriorities.Normal,CreatedByUserId=users["requester"].Id,CreatedAt=fixedAt};var driverAssignment=new FleetAssignment{FleetRequest=driverRequest,Vehicle=vehicle,DriverUser=users["driver"],AssignedByUser=users["dispatcher"],AssignedAt=fixedAt.AddHours(8),IsActive=true,AssignmentStatus=FleetAssignmentStatuses.Assigned};var driverTrip=new FleetTripRecord{FleetRequest=driverRequest,Assignment=driverAssignment,DriverUser=users["driver"],ActualStartAt=fixedAt.AddHours(9),StartMileage=1040};var draftRequest=new FleetRequest{RequestNo=$"VH-DF-{Guid.NewGuid():N}"[..20],RequesterUser=users["requester"],RequesterDepartment=department,RequestDate=new DateOnly(2026,8,1),Purpose="M4.2 request capabilities",MissionType="QA",Destination="QA Draft",ContactPersonName="QA",ContactPhone="0000",DepartureAt=fixedAt.AddHours(12),ExpectedReturnAt=fixedAt.AddHours(13),PassengerCount=1,Status=FleetRequestStatuses.Draft,Priority=FleetPriorities.Normal,CreatedByUserId=users["requester"].Id,CreatedAt=fixedAt};
    var draftPassenger=new FleetRequestPassenger{FleetRequest=draftRequest,User=users["requester"],FullName=users["requester"].FullName,PassengerType=FleetPassengerTypes.Employee,IsRequester=true,SortOrder=1};
    var attachmentRequest=new FleetRequest{RequestNo=$"VH-AT-{Guid.NewGuid():N}"[..20],RequesterUser=users["requester"],RequesterDepartment=department,RequestDate=new DateOnly(2026,8,1),Purpose="M4.2 attachment lifecycle",MissionType="QA",Destination="QA Attachment",ContactPersonName="QA",ContactPhone="0000",DepartureAt=fixedAt.AddHours(15),ExpectedReturnAt=fixedAt.AddHours(17),PassengerCount=1,Status=FleetRequestStatuses.InProgress,Priority=FleetPriorities.Normal,CreatedByUserId=users["requester"].Id,CreatedAt=fixedAt};var attachmentAssignment=new FleetAssignment{FleetRequest=attachmentRequest,Vehicle=attachmentVehicle,DriverUser=users["previousDriver"],AssignedByUser=users["dispatcher"],AssignedAt=fixedAt.AddHours(14),IsActive=true,AssignmentStatus=FleetAssignmentStatuses.Assigned};var attachmentTrip=new FleetTripRecord{FleetRequest=attachmentRequest,Assignment=attachmentAssignment,DriverUser=users["previousDriver"],ActualStartAt=fixedAt.AddHours(15),StartMileage=2000};db.AddRange(emergencyQueueRequest,driverRequest,driverAssignment,driverTrip,draftRequest,draftPassenger,attachmentRequest,attachmentAssignment,attachmentTrip);
    await db.SaveChangesAsync(); return new(runId, fixedAt, vehicle.Id, schedule.Id, request.Id, emergencyQueueRequest.Id, driverRequest.Id, draftRequest.Id, driverAssignment.Id, driverTrip.Id, attachmentRequest.Id, attachmentAssignment.Id, attachmentTrip.Id, attachmentVehicle.Id, assignment.Id, trip.Id, document.Id, rollout.Id, capability.Id,mismatchCapability.Id,safetyCapability.Id,policy.Id,policy.Code,department.Id,users.ToDictionary(x => x.Key, x => new QaUser(x.Value.Id, x.Value.Username)));
}
static IEnumerable<string> Permissions(string role, string[] all) => role switch { "admin" => all, "dashboard" => [FleetPermissions.DashboardView, FleetPermissions.ReportView, FleetPermissions.ReportExport, FleetPermissions.CalendarView, FleetPermissions.MaintenanceView], "noOverride" => [FleetPermissions.MaintenanceView, FleetPermissions.MaintenanceManage, FleetPermissions.MaintenanceComplete,FleetPermissions.CapabilityView,FleetPermissions.CompatibilityView], "driver" or "previousDriver" => [FleetPermissions.DriverViewOwnJobs,FleetPermissions.DriverAcknowledge,FleetPermissions.DriverStart,FleetPermissions.DriverComplete,FleetPermissions.TripUploadAttachment], "requester"=>[FleetPermissions.RequestViewOwn,FleetPermissions.RequestCreate,FleetPermissions.RequestEditOwn,FleetPermissions.RequestSubmit,FleetPermissions.RequestCapabilityManageOwn,FleetPermissions.CompatibilityView,FleetPermissions.EmergencyCreate,FleetPermissions.EmergencyViewOwn],"dispatcher"=>[FleetPermissions.DispatchView,FleetPermissions.DispatchAssign,FleetPermissions.CompatibilityView,FleetPermissions.EmergencyViewQueue,FleetPermissions.EmergencyDispatch],"reviewer"=>[FleetPermissions.RequestViewOwn,FleetPermissions.RequestCreate,FleetPermissions.RequestEditOwn,FleetPermissions.RequestSubmit,FleetPermissions.AdminReviewApprove,FleetPermissions.AdminReviewReturn,FleetPermissions.AdminReviewReject,FleetPermissions.CalendarView,FleetPermissions.EmergencyReview,FleetPermissions.EmergencyViewAudit],"director"=>[FleetPermissions.RequestViewOwn,FleetPermissions.RequestCreate,FleetPermissions.RequestEditOwn,FleetPermissions.RequestSubmit,FleetPermissions.DirectorApprove,FleetPermissions.DirectorReturn,FleetPermissions.DirectorReject,FleetPermissions.CalendarView],_ => [FleetPermissions.MaintenanceView] };
static async Task Cleanup(AppDbContext db, QaManifest m)
{
    await using var tx = await db.Database.BeginTransactionAsync();
    var userIds = m.Users.Values.Select(x => x.Id).ToArray();
    if(!m.RunId.StartsWith("qa-",StringComparison.Ordinal)||userIds.Length<7)throw new InvalidOperationException("Manifest run identity is invalid.");
    var ownedUsers=await db.Users.CountAsync(x=>userIds.Contains(x.Id)&&x.Username.StartsWith(m.RunId));
    if(ownedUsers!=userIds.Length||!await db.Departments.AnyAsync(x=>x.Id==m.DepartmentId&&x.Name.StartsWith(m.RunId)))throw new InvalidOperationException("Manifest ownership validation failed.");
    var manifestRequestIds=new[]{m.RequestId,m.EmergencyQueueRequestId,m.DriverRequestId,m.DraftRequestId,m.AttachmentRequestId};
    if(await db.FleetRequests.CountAsync(x=>manifestRequestIds.Contains(x.Id)&&userIds.Contains(x.CreatedByUserId))!=manifestRequestIds.Length)throw new InvalidOperationException("Manifest contains a request outside its run.");
    var requestIds = await db.FleetRequests.Where(x=>userIds.Contains(x.CreatedByUserId)).Select(x=>x.Id).ToArrayAsync();
    var runSuffix = m.RunId.Substring(m.RunId.Length - 8);
    var vehicleIds = await db.FleetVehicles.Where(x => x.VehicleCode.Contains(runSuffix)).Select(x => x.Id).ToListAsync();
    var maintenanceIds = await db.FleetVehicleMaintenanceSchedules.Where(x => vehicleIds.Contains(x.VehicleId)).Select(x => x.Id).ToListAsync();
    var aggregateIds = vehicleIds.Concat(maintenanceIds).Concat(requestIds).Concat([m.AssignmentId, m.TripId, m.DriverAssignmentId, m.DriverTripId, m.AttachmentAssignmentId, m.AttachmentTripId, m.DocumentId]).Distinct().ToArray();
    var eventIds = await db.DomainEvents.Where(x => aggregateIds.Contains(x.AggregateId) || (x.ActorUserId.HasValue && userIds.Contains(x.ActorUserId.Value))).Select(x => x.EventId).ToListAsync();
    var outboxIds = await db.OutboxMessages.Where(x => eventIds.Contains(x.EventId)).Select(x => x.Id).ToListAsync();

    await db.NotificationDeliveries.Where(x => outboxIds.Contains(x.OutboxMessageId) || userIds.Contains(x.RecipientUserId)).ExecuteDeleteAsync();
    await db.Notifications.Where(x => x.UserId.HasValue && userIds.Contains(x.UserId.Value)).ExecuteDeleteAsync();
    await db.LineDeliveryLogs.Where(x => x.RecipientUserId.HasValue && userIds.Contains(x.RecipientUserId.Value)).ExecuteDeleteAsync();
    await db.OutboxMessages.Where(x => outboxIds.Contains(x.Id)).ExecuteDeleteAsync();
    await db.DomainEvents.Where(x => eventIds.Contains(x.EventId)).ExecuteDeleteAsync();
    await db.RefreshTokens.Where(x => userIds.Contains(x.UserId)).ExecuteDeleteAsync();
    await db.AuditLogs.Where(x => (x.UserId.HasValue && userIds.Contains(x.UserId.Value)) || (x.EffectiveActorUserId.HasValue && userIds.Contains(x.EffectiveActorUserId.Value))).ExecuteDeleteAsync();
    await db.FleetMaintenanceAttachments.Where(x => userIds.Contains(x.CreatedByUserId)).ExecuteDeleteAsync();
    await db.FleetTripAttachments.Where(x=>userIds.Contains(x.CreatedByUserId)).ExecuteDeleteAsync();
    await db.FleetVehicleMaintenanceRecords.Where(x => vehicleIds.Contains(x.VehicleId)).ExecuteDeleteAsync();
    await db.FleetVehicleMaintenanceSchedules.Where(x => vehicleIds.Contains(x.VehicleId)).ExecuteDeleteAsync();
    await db.FleetVehicleDocuments.Where(x => vehicleIds.Contains(x.VehicleId)).ExecuteDeleteAsync();
    await db.FleetCancellationRequests.Where(x => requestIds.Contains(x.FleetRequestId)).ExecuteDeleteAsync();
    await db.FleetEmergencyPostReviews.Where(x=>requestIds.Contains(x.FleetRequestId)).ExecuteDeleteAsync();
    await db.FleetCompatibilityOverrides.Where(x=>requestIds.Contains(x.FleetRequestId)).ExecuteDeleteAsync();
    await db.FleetRequestRequiredCapabilities.Where(x=>requestIds.Contains(x.FleetRequestId)).ExecuteDeleteAsync();
    await db.FleetTripRecords.Where(x => requestIds.Contains(x.FleetRequestId)).ExecuteDeleteAsync();
    await db.FleetAssignments.Where(x => requestIds.Contains(x.FleetRequestId)).ExecuteDeleteAsync();
    await db.FleetRequestStatusHistories.Where(x => requestIds.Contains(x.FleetRequestId)).ExecuteDeleteAsync();
    await db.FleetRequestPassengers.Where(x => requestIds.Contains(x.FleetRequestId)).ExecuteDeleteAsync();
    await db.FleetRequests.Where(x => requestIds.Contains(x.Id)).ExecuteDeleteAsync();
    await db.FleetVehicleUnavailability.Where(x => vehicleIds.Contains(x.VehicleId)).ExecuteDeleteAsync();
    await db.FleetDriverUnavailability.Where(x => userIds.Contains(x.UserId)).ExecuteDeleteAsync();
    await db.FleetDriverProfiles.Where(x => userIds.Contains(x.UserId)).ExecuteDeleteAsync();
    await db.FleetVehicleCapabilities.Where(x=>vehicleIds.Contains(x.VehicleId)).ExecuteDeleteAsync();
    var typeIds = await db.FleetVehicles.Where(x => vehicleIds.Contains(x.Id)).Select(x => x.VehicleTypeId).ToListAsync();
    await db.FleetVehicles.Where(x => vehicleIds.Contains(x.Id)).ExecuteDeleteAsync();
    await db.FleetVehicleTypes.Where(x => typeIds.Contains(x.Id)).ExecuteDeleteAsync();
    await db.FleetMaintenanceTypes.Where(x => x.Name.StartsWith(m.RunId)).ExecuteDeleteAsync();
    await db.FleetCapabilities.Where(x=>x.Id==m.CapabilityId||x.Id==m.SafetyCapabilityId||(x.CreatedByUserId.HasValue&&userIds.Contains(x.CreatedByUserId.Value))).ExecuteDeleteAsync();
    await db.FleetEmergencyPolicies.Where(x=>x.Id==m.EmergencyPolicyId).ExecuteDeleteAsync();
    await db.FleetRolloutSettings.Where(x => x.Id == m.RolloutSettingId).ExecuteDeleteAsync();
    await db.UserRoles.Where(x => userIds.Contains(x.UserId)).ExecuteDeleteAsync();
    var roleIds = await db.Roles.Where(x => x.Name.StartsWith(m.RunId)).Select(x => x.Id).ToListAsync();
    await db.RolePermissions.Where(x => roleIds.Contains(x.RoleId)).ExecuteDeleteAsync();
    await db.Roles.Where(x => roleIds.Contains(x.Id)).ExecuteDeleteAsync();
    await db.Users.Where(x => userIds.Contains(x.Id)).ExecuteDeleteAsync();
    await db.Departments.Where(x => x.Name.StartsWith(m.RunId)).ExecuteDeleteAsync();
    await tx.CommitAsync();
}
static string Required(string key) => Environment.GetEnvironmentVariable(key) ?? throw new InvalidOperationException($"{key} is required.");
record QaManifest(string RunId, DateTime FixedAt, Guid VehicleId, Guid MaintenanceId, Guid RequestId, Guid EmergencyQueueRequestId, Guid DriverRequestId, Guid DraftRequestId, Guid DriverAssignmentId, Guid DriverTripId, Guid AttachmentRequestId, Guid AttachmentAssignmentId, Guid AttachmentTripId, Guid AttachmentVehicleId, Guid AssignmentId, Guid TripId, Guid DocumentId, Guid RolloutSettingId,Guid CapabilityId,Guid MismatchCapabilityId,Guid SafetyCapabilityId,Guid EmergencyPolicyId,string EmergencyPolicyCode,Guid DepartmentId, Dictionary<string, QaUser> Users); record QaUser(Guid Id, string Username);
